### ISSUE TITLE
Speed of movement

### ISSUE THREAD

**Issue by davidfhudson** [reptilex/tesla-style-solar-power-card#10]
Can you please guide how to calibrate the speed of the balls that move? I have quite high usage so would like to change the upper bounds for example of what represents "fast" or "slow" moving?

**Comment by reptilex** [comment]
The last function of the js class controls the speed. If you want it to slow down change lower the value of the speed function on line 649.
`speed = 0.07 * value;`
to 0.03*value or something like that.
https://github.com/reptilex/tesla-style-solar-power-card/blob/ae610374988083f0be0ac2c992620d27076f18f7/tesla-style-solar-power-card.js#L649

**Comment by reptilex** [comment]
You can of course change the function into whatever you want, maybe log function would be good if you want to have a steadier flow. My approach was to get a feel of the actual flow, therefore I prefer it to be a linear function.

**Comment by davidfhudson** [comment]
Thanks. Will play with that - its straightforward enough. I like the linear flow too.
