### ISSUE TITLE
card is TINY

### ISSUE THREAD

**Issue by guybw** [reptilex/tesla-style-solar-power-card#100]
I'm not sure if this is a HA issue or this card issue but on my phone it works great but on a PC ( Windows 10 / Edge/Firefox/Chrome) it shows as follows:
![image](https://user-images.githubusercontent.com/64648444/149556348-939e22c7-371c-436b-aa50-c27e3ae9d418.png)

Any ideas on how I could fix it?

**Comment by Subia75** [comment]
It is a visual problem when you enter the edit, 
if you close edit dashboard and refresh with F5 the browser returns to work correctly

**Comment by guybw** [comment]
Thank you! Yes, that was the issue.
