### ISSUE TITLE
Completely stopped on core-2022.2.0

### ISSUE THREAD

**Issue by neildsb** [reptilex/tesla-style-solar-power-card#104]
just upgraded to core-2022.2.0, everything has stopped :-( using stock Powerwall templates

![image](https://user-images.githubusercontent.com/91122872/152302768-2915abdd-9c44-45cb-9ac2-fd0a994fb86d.png)

**Comment by piriript** [comment]
I have the same Problem

**Comment by neildsb** [comment]
if it helps?

Logger: homeassistant.helpers.template
Source: helpers/template.py:1286
First occurred: 8:24:57 am (1050 occurrences)
Last logged: 0:46:07 pm

Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ ((states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float ) - (states('sensor.tesla_card_battery_charging_inside') | float) ) | round(1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'float' got invalid input 'unknown' when rendering template '{{ ((states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float ) - (states('sensor.tesla_card_battery_charging_inside') | float) ) | round(1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1

**Comment by neildsb** [comment]
I fixed it by removing the min and max, not sure if this is a good solution? - max(0) & min(0)

template:
  - sensor:
      - name: "Tesla Card Grid Consumption"
        unique_id: "tesla_card_grid_consumption"
        state: "{{ states('sensor.powerwall_site_now') | float | round(1) }}"
        device_class: power
        unit_of_measurement: kW

      - name: "Tesla Card Grid Feed In"
        unique_id: "tesla_card_grid_feed_in"
        state: "{{ states('sensor.powerwall_site_now') | float | abs | round(1) }}"
        device_class: power
        unit_of_measurement: kW

      - name: "Tesla Card Solar Consumption"
        unique_id: "tesla_card_solar_consumption"
        state: "{{ ((states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float ) - (states('sensor.tesla_card_battery_charging_inside') | float) ) | round(1) }}"
        device_class: power
        unit_of_measurement: kW

      - name: "Tesla Card Battery Consumption"
        unique_id: "tesla_card_battery_consumption"
        state: "{{ states('sensor.powerwall_battery_now') | float | round(1) }}"
        device_class: power
        unit_of_measurement: kW

      - name: "Tesla Card Battery Charging Inside"
        unique_id: "tesla_card_battery_charging_inside"
        state: "{{ states('sensor.powerwall_battery_now') | float | abs | round(1) }}"
        device_class: power
        unit_of_measurement: kW

**Comment by neildsb** [comment]
I followed this https://community.home-assistant.io/t/sensor-not-working-after-update-to-2022-2/387940/4

**Comment by neildsb** [comment]
spoke too soon, its not working 100%
![image](https://user-images.githubusercontent.com/91122872/152361873-54fdf94b-50f1-446b-b084-0fc45fae5781.png)
![image](https://user-images.githubusercontent.com/91122872/152362181-e956ba0c-6f67-4591-a83a-2493eeee4fd4.png)

**Comment by piriript** [comment]
try this :
carefull with power direction, in my case gridpower is positive for consumption negative for feedin
do the same thing for battery:


>   tesla_card_grid_consumption:
>           unique_id: 'tesla_card_5fee6ddd5c1f42a099067ce9dd44e6d1'   
>           value_template: >-
>               {% if states('sensor.Victron_GridPower')|float >= 0 %}  {{ states('sensor.Victron_GridPower') | float | round(1) }}
>               {% else %} 0.0
>               {% endif %}
>           availability_template:  "{{ states('sensor.Victron_GridPower') not in ['unknown', 'unavailable']  }}">         
>           device_class: power
>           unit_of_measurement: W
>  tesla_card_grid_feed_in:
>           unique_id: 'tesla_card_52d22b847ade42c5b4526b2ff15f5aef'     
>           value_template: >-
>               {% if states('sensor.Victron_GridPower')|float < 0 %}  {{ states('sensor.Victron_GridPower') | float | abs | round(1) }}
>               {% else %} 0.0
>               {% endif %}
>           availability_template:  "{{ states('sensor.Victron_GridPower') not in ['unknown', 'unavailable']  }}"
>           device_class: power
>           unit_of_measurement: W
> 
>

**Comment by dcod3d** [comment]
This is working for me
```  - sensor:
    - name: "Tesla Card Grid Consumption"
      unique_id: 'tesla_card_grid_consumption'
      state: "{{ [ states('sensor.powerwall_site_now') | float(0),0] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Grid Feed In"
      unique_id: 'tesla_card_grid_feed_in'
      state: "{{ [ states('sensor.powerwall_site_now') | float(0),0] | min | abs | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Solar Consumption"
      unique_id: 'tesla_card_solar_consumption'
      state: "{{ ((states('sensor.powerwall_solar_now') | float(0)) - (states('sensor.tesla_card_grid_feed_in') | float(0) ) - (states('sensor.tesla_card_battery_charging') | float(0)) ) | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Battery Consumption"
      unique_id: 'tesla_card_battery_consumption'
      state: "{{ [ states('sensor.powerwall_battery_now') | float(0),0] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Battery Charging"
      unique_id: 'tesla_card_battery_charging'
      state: "{{ [ states('sensor.powerwall_battery_now') | float(0),0] | min | abs | round(1) }}"
      device_class: power
      unit_of_measurement: kW```

**Comment by neildsb** [comment]
> This is working for me
> 
> ```
>     - name: "Tesla Card Grid Consumption"
>       unique_id: 'tesla_card_grid_consumption'
>       state: "{{ [ states('sensor.powerwall_site_now') | float(0),0] | max | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Grid Feed In"
>       unique_id: 'tesla_card_grid_feed_in'
>       state: "{{ [ states('sensor.powerwall_site_now') | float(0),0] | min | abs | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Solar Consumption"
>       unique_id: 'tesla_card_solar_consumption'
>       state: "{{ ((states('sensor.powerwall_solar_now') | float(0)) - (states('sensor.tesla_card_grid_feed_in') | float(0) ) - (states('sensor.tesla_card_battery_charging') | float(0)) ) | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Battery Consumption"
>       unique_id: 'tesla_card_battery_consumption'
>       state: "{{ [ states('sensor.powerwall_battery_now') | float(0),0] | max | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Battery Charging"
>       unique_id: 'tesla_card_battery_charging'
>       state: "{{ [ states('sensor.powerwall_battery_now') | float(0),0] | min | abs | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> ```

looks good, thanks really appreciate it, will doble check then the sun rises tomorrow :-)

![image](https://user-images.githubusercontent.com/91122872/152423587-49799638-bcd1-4d99-aa8a-915d4bebe0cf.png)

**Comment by billhoz** [comment]
Above templates worked for me and sorted the issue - thanks for the help

**Comment by neildsb** [comment]
the solar is not working :-(

![image](https://user-images.githubusercontent.com/91122872/152507878-98aed0e6-8893-453f-921f-e9294d08f18b.png)

**Comment by AndrewTapp** [comment]
This had been working for a long time on my setup, probably about a week ago this stopped working and am now on 'Home Assistant 2022.2.3' but still no luck getting it working.

This is the error I'm getting in HomeAssistant.

`2022-02-07 11:03:39 ERROR (MainThread) [frontend.js.latest.202202030] http://192.168.1.240:8123/local/tesla-style-solar-power-card.js:14:9 Uncaught SyntaxError: Unexpected identifier`

Any help would be appreciated.

**Comment by neildsb** [comment]
2022.2.3 broke a few other things (Miele HACS integration) so rolled back to 2022.2.2, if it helps?

**Comment by AndrewTapp** [comment]
Many thanks for that, it's been broken since 2022.2.1, the last one it worked on for me was 2022.1.1

**Comment by robertfgoodworth** [comment]
None of the above works for me on the latest HA version, PLEASE look into fixing it, have grown to love this card. It's on my main page.

**Comment by reptilex** [comment]
Just to make this clear, it's not about the card. This is something related to the templates and how they are built.
The card works fine with core-2022.2.8. You have to test your templates and if they are working correctly. If this is the case make sure the templates for HA have the right "direction" as stated in the howto they need to be positive.

**Comment by billhoz** [comment]
For what it's worth, this entry in config works for me after release 2022.2.5 - hope it helps

template:
  - sensor:
    - name: "Tesla Card Grid Consumption"
      unique_id: 'tesla_card_grid_consumption'
      state: "{{ [ states('sensor.powerwall_site_now') | float,0] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Grid Feed In"
      unique_id: 'tesla_card_grid_feed_in'
      state: "{{ [ states('sensor.powerwall_site_now') | float,0] | min | abs | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Solar Consumption"
      unique_id: 'tesla_card_solar_consumption'
      state: "{{ ((states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float) - (states('sensor.tesla_card_battery_charging_inside') | float) ) | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Battery Consumption"
      unique_id: 'tesla_card_battery_consumption'
      state: "{{ [ states('sensor.powerwall_battery_now') | float,0] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Battery Charging"
      unique_id: 'tesla_card_battery_charging'
      state: "{{ [ states('sensor.powerwall_battery_now') | float,0] | min | abs | round(1) }}"
      device_class: power
      unit_of_measurement: kW

**Comment by billhoz** [comment]
something changed in formatting from copy/paste to upload I've attached thhe original file
[Tesla card config tempalte extract 210225.txt](https://github.com/reptilex/tesla-style-solar-power-card/files/8139909/Tesla.card.config.tempalte.extract.210225.txt)

**Comment by robertfgoodworth** [comment]
> * ('sensor.tesla_card_battery_charging_inside')

Hi billhoz,  thanks for the help,  umm  i think i'm missing something,  in your text file where does "('sensor.tesla_card_battery_charging_inside')"  come from?  i don't hgave that sensor anywhere.

**Comment by billhoz** [comment]
Hi that sensor appears in the orginal documents under the setup for Tesla Powerwall [https://github.com/reptilex/tesla-style-solar-power-card#tesla-powerwall-usage] - it's in the Solar Consumption template - need to scroll to end of line...

**Comment by Avatar1976** [comment]
Hello my dear learned friends, based on your successes above I have reworked my config which covers most scenarios (which I was going to approach the author at some point until it broke with the core update), this works even for charging the battery from the grid.

`
sensor:
    - name: "Tesla Card Grid Consumption"
      unique_id: 'tesla_card_grid_consumption'
      state: "{{ [ ((states('sensor.powerwall_site_now') | float) - ([(([states('sensor.powerwall_site_now') | float , 0] | max | abs ) - (states('sensor.powerwall_load_now') | float)) | float , 0] | max | abs)) | float , 0 ] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Grid Feed In"
      unique_id: 'tesla_card_grid_feed_in'
      state: "{{ [ states('sensor.powerwall_site_now') | float , 0 ] | min | abs | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Solar Consumption"
      unique_id: 'tesla_card_solar_consumption'
      state: "{{ [ (states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float ) - (states('sensor.tesla_card_battery_charging_inside') | float) | float , 0 ] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Battery Consumption"
      unique_id: 'tesla_card_battery_consumption'
      state: "{{ [ states('sensor.powerwall_battery_now') | float , 0 ] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW
      
    - name: "Tesla Card Battery Export"
      unique_id: 'tesla_card_battery_export'
      state: "{{ [ (( [ states('sensor.powerwall_battery_now') | float , 0 ] | max ) - ( [ states('sensor.powerwall_load_now') | float , 0 ] | max )) | float , 0 ] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW

    - name: "Tesla Card Battery Charging Inside"
      unique_id: 'tesla_card_battery_charging_inside'
      state: "{{ [ (([ states('sensor.powerwall_battery_now') | float , 0 ] | min | abs) - ([(([ states('sensor.powerwall_site_now') | float , 0 ] | max | abs ) - (states('sensor.powerwall_load_now') | float)) | float , 0 ] |  max |abs)) | float , 0 ] | max | round(1) }}"
      device_class: power
      unit_of_measurement: kW
      
    - name: "Tesla Card Battery Charging Outside"
      unique_id: 'tesla_card_battery_charging_outside'
      state: "{{ [ (([states('sensor.powerwall_site_now') | float , 0 ] | max | abs ) - (states('sensor.powerwall_load_now') | float)) | float , 0 ] | max | abs | round(1) }}"
      device_class: power
      unit_of_measurement: kW`

The main one that's different to what others would have is the Tesla Battery Charging Outside sensor template calc.
From here all you need to do is call it within your lovelace config for your Tesla style power card:
`grid_to_battery_entity: sensor.tesla_card_battery_charging_outside`

Also this is untested as I can't send to the grid from my battery (someone with a VPP might help test here):
`battery_to_grid_entity: sensor.tesla_card_battery_export`

**Comment by Avatar1976** [comment]
@reptilex If you wanted to update your instructions to the above for the main repo page it would be my honour to contribute.  The instructions on the main page are completely broken as indicated above from core-2022.2.0 .

**Comment by ziptbm** [comment]
> Hello my dear learned friends, based on your successes above I have reworked my config which covers most scenarios (which I was going to approach the author at some point until it broke with the core update), this works even for charging the battery from the grid.
> 
> ```
> sensor:
>     - name: "Tesla Card Grid Consumption"
>       unique_id: 'tesla_card_grid_consumption'
>       state: "{{ [ ((states('sensor.powerwall_site_now') | float) - ([(([states('sensor.powerwall_site_now') | float , 0] | max | abs ) - (states('sensor.powerwall_load_now') | float)) | float , 0] | max | abs)) | float , 0 ] | max | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Grid Feed In"
>       unique_id: 'tesla_card_grid_feed_in'
>       state: "{{ [ states('sensor.powerwall_site_now') | float , 0 ] | min | abs | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Solar Consumption"
>       unique_id: 'tesla_card_solar_consumption'
>       state: "{{ [ (states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float ) - (states('sensor.tesla_card_battery_charging_inside') | float) | float , 0 ] | max | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Battery Consumption"
>       unique_id: 'tesla_card_battery_consumption'
>       state: "{{ [ states('sensor.powerwall_battery_now') | float , 0 ] | max | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
>       
>     - name: "Tesla Card Battery Export"
>       unique_id: 'tesla_card_battery_export'
>       state: "{{ [ (( [ states('sensor.powerwall_battery_now') | float , 0 ] | max ) - ( [ states('sensor.powerwall_load_now') | float , 0 ] | max )) | float , 0 ] | max | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> 
>     - name: "Tesla Card Battery Charging Inside"
>       unique_id: 'tesla_card_battery_charging_inside'
>       state: "{{ [ (([ states('sensor.powerwall_battery_now') | float , 0 ] | min | abs) - ([(([ states('sensor.powerwall_site_now') | float , 0 ] | max | abs ) - (states('sensor.powerwall_load_now') | float)) | float , 0 ] |  max |abs)) | float , 0 ] | max | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
>       
>     - name: "Tesla Card Battery Charging Outside"
>       unique_id: 'tesla_card_battery_charging_outside'
>       state: "{{ [ (([states('sensor.powerwall_site_now') | float , 0 ] | max | abs ) - (states('sensor.powerwall_load_now') | float)) | float , 0 ] | max | abs | round(1) }}"
>       device_class: power
>       unit_of_measurement: kW
> ```
> 
> The main one that's different to what others would have is the Tesla Battery Charging Outside sensor template calc. From here all you need to do is call it within your lovelace config for your Tesla style power card: `grid_to_battery_entity: sensor.tesla_card_battery_charging_outside`
> 
> Also this is untested as I can't send to the grid from my battery (someone with a VPP might help test here): `battery_to_grid_entity: sensor.tesla_card_battery_export`

This is great.  Especially adding the Grid to Battery Entity.  I updated my config to match yours and rebooted, but I'm still seeing a Template Warning for 'float' error in my logs.

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1286
First occurred: 21:55:59 (2 occurrences)
Last logged: 21:55:59

`Template warning: 'float' got invalid input 'unknown' when rendering template '{{ [ (states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float ) - (states('sensor.tesla_card_battery_charging_inside') | float) | float , 0 ] | max | round(1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1`
```

@Avatar1976 are you seeing this same error in your logs?

**Comment by Avatar1976** [comment]
> @Avatar1976 are you seeing this same error in your logs?
@ziptbm yep I am looks to be rendering ok for me though, issue seems to be around default values... Probably fine for most intents and purposes.  I suppose if you were passing an undefined data source through float it would likely have an issue.  IE at start up before the powerwall sensors start returning a value?

**Comment by Avatar1976** [comment]
Just a thought, and this is likely why the people above are specifying all float as float(0), as although the default value is suppose to be 0.0 there must have been some changes to the specification from 2022.1 onward to not return 0 when fed an undefined value...
My syntax is correct as per:
https://www.home-assistant.io/docs/configuration/templating/ 
But that doesn't mean this doco is up to date I guess and undefined / null values are always sh!t to deal with in most programming languages and open to change.  I'll do some revisions and come back to you @ziptbm, obvious choice for me is to replace all float declarations with float(0) and retest.   Hoping someone out there has a VPP to test sending power to the grid from battery too...

**Comment by Avatar1976** [comment]
@neildsb care to check the VPP out as per above?

**Comment by neildsb** [comment]
> @neildsb care to check the VPP out as per above?

Will give it a go tomorrow 😉

**Comment by neildsb** [comment]
just tried it, grid to batter looks good, a little off centre :-( I can test battery to grid tomorrow around 4pm GMT when it dumps

![image](https://user-images.githubusercontent.com/91122872/159374943-4ef23855-e549-4949-95ce-8c8b312f8bfc.png)

**Comment by Avatar1976** [comment]
> just tried it, grid to batter looks good, a little off centre :-( I can test battery to grid tomorrow around 4pm GMT when it dumps
There is an option to hide inactive flows with:
`hide_inactive_lines: 1
`
Put that in your lovelace config. 
Good stuff just to speak to the concern worried that I need to subtract the battery export flow to grid from the general battery consumption flow. But didn't want to overthink it until someone confirms it's actually a problem. 
And re the float(0) thing please make sure you guys are copying from my (edited) post not anyone else's replies (which I can't edit by their nature) . 😂

**Comment by neildsb** [comment]
> > just tried it, grid to batter looks good, a little off centre :-( I can test battery to grid tomorrow around 4pm GMT when it dumps
> > There is an option to hide inactive flows with:
> > `hide_inactive_lines: 1 `
> > Put that in your lovelace config.
> > Good stuff just to speak to the concern worried that I need to subtract the battery export flow to grid from the general battery consumption flow. But didn't want to overthink it until someone confirms it's actually a problem.
> > And re the float(0) thing please make sure you guys are copying from my (edited) post not anyone else's replies (which I can't edit by their nature) . 😂

nice thanks
![image](https://user-images.githubusercontent.com/91122872/159379700-98e03eb7-7c35-4024-9063-c64f5eed927b.png)

have also copied ur updated float code up to 'Tesla Card Battery Charging Outside', all good, will update tomorrow, good night all

**Comment by neildsb** [comment]
one last comment for the night, if it helps others - a side note, I added an AMPs sensor using the PW feed, we popped the main 100AMP fuse one night, opps, 2 cars, 1 PW charging, house baseload and a hot tub = melted fuse so I wanted to keep an eye on it -

    sensors:
      amps_used:
        value_template: "{{ ((1000 * states('sensor.powerwall_site_now')|float) / 230)|round(2) }}"

![image](https://user-images.githubusercontent.com/91122872/159380576-edf552a9-375d-43aa-b8cb-aa27def8a349.png)

type: custom:button-card
entity: sensor.amps_used
icon: mdi:home-lightning-bolt-outline
name: AMPS
layout: icon_state_name2nd
styles:
  card:
    - background-color: |
        [[[
          if (entity.state <= 10) return 'yellowgreen';
          if (entity.state <= 20) return 'gold';
          if (entity.state <= 50) return 'orange';
          else return 'Crimson';
        ]]]
    - animation: |
        [[[
          if (entity.state >= 50) return 'blink 2s ease infinite';
        ]]]
    - font-size: 30px
    - height: 108px
    - width: 390px
  icon:
    - color: white
show_label: true
show_name: true
show_state: true

**Comment by Avatar1976** [comment]
> one last comment for the night, if it helps others - a side note, I added an AMPs sensor using the PW feed, we popped the main 100AMP fuse one night, opps, 2 cars, 1 PW charging, house baseload and a hot tub = melted fuse so I wanted to keep an eye on it -
> 

That's a lot of energy usage! 😂

**Comment by ziptbm** [comment]
@Avatar1976 thanks for the test and updates to your configuration yaml in[ this post](https://github.com/reptilex/tesla-style-solar-power-card/issues/104#issuecomment-1073373803).

What are the three new items added to the end for?  e.g. Tesla Card HWS Today, Export Electricity Neg, and Tessy Charger Power?

**Comment by Avatar1976** [comment]
> @Avatar1976 thanks for the test and updates to your configuration yaml in[ this post](https://github.com/reptilex/tesla-style-solar-power-card/issues/104#issuecomment-1073373803).
> 
> What are the three new items added to the end for? e.g. Tesla Card HWS Today, Export Electricity Neg, and Tessy Charger Power?



Because copy paste fail, sorry will remove those, was just trying to get HWS output for the day, Exported electricity as a negative because I was messing around and the last one gives the attribute value out of the Tesla HACS integration as kW throughput instead of km/h (which I think is useless info).

**Comment by ziptbm** [comment]
@Avatar1976  - all good, thanks for your help and quick responses! 

What is HWS?

**Comment by Avatar1976** [comment]
> @Avatar1976 - all good, thanks for your help and quick responses!
> 
> What is HWS?

Hot Water System 😂

**Comment by neildsb** [comment]
Good morning, I have a few problems, Solar and battery values are not correct :-(

![image](https://user-images.githubusercontent.com/91122872/159437481-a6096a12-ac97-487a-93fb-3b69b259c938.png)

**Comment by Avatar1976** [comment]
> Good morning, I have a few problems, Solar and battery values are not correct :-(
> 
> ![image](https://user-images.githubusercontent.com/91122872/159437481-a6096a12-ac97-487a-93fb-3b69b259c938.png)

Interesting issue can you share your lovelace config?  Maybe naming discrepancies?

**Comment by neildsb** [comment]
thanks, will do a scrub in a sec - 

type: custom:tesla-style-solar-power-card
house_entity: sensor.powerwall_load_now
grid_entity: sensor.tesla_card_grid_consumption
battery_entity: sensor.tesla_card_battery_consumption
generation_entity: sensor.powerwall_solar_now
generation_to_grid_entity: sensor.tesla_card_grid_feed_in
generation_to_house_entity: sensor.tesla_card_solar_consumption
generation_to_battery_entity: sensor.tesla_card_battery_charging
battery_to_house_entity: sensor.tesla_card_battery_consumption
grid_to_house_entity: sensor.tesla_card_grid_consumption
battery_extra_entity: sensor.powerwall_charge
grid_to_battery_entity: sensor.tesla_card_battery_charging_outside
battery_to_grid_entity: sensor.tesla_card_battery_export
hide_inactive_lines: 1

**Comment by neildsb** [comment]
found it thanks -

![image](https://user-images.githubusercontent.com/91122872/159455392-9c5a0fda-5c54-464a-bf03-7dec6cc36195.png)

![image](https://user-images.githubusercontent.com/91122872/159455534-d43c4f52-3d88-49a9-a35f-afac9373787b.png)

**Comment by Avatar1976** [comment]
> found it thanks -
> 
> ![image](https://user-images.githubusercontent.com/91122872/159455392-9c5a0fda-5c54-464a-bf03-7dec6cc36195.png)
> 
> ![image](https://user-images.githubusercontent.com/91122872/159455534-d43c4f52-3d88-49a9-a35f-afac9373787b.png)
> 
> Ps have a reminder to check the battery export @ 4pm GMT
> 
> also running Version core-2022.3.5 Operating System, Home Assistant OS 7.5

Great looks good!

**Comment by Avatar1976** [comment]
> As promised here is my output, not quite there ☹
> 
> ![image](https://user-images.githubusercontent.com/91122872/159524363-8885680d-b9c0-4180-8fb3-63b25c07bc2a.png)

Ah OK, the grid, house and battery I kind of expected to screw up due to not minusing your battery to grid output from the battery to house consumption. The solar output getting messed up there I can't explain though.

**Comment by Avatar1976** [comment]
![Screenshot_20220323-065539_Home Assistant](https://user-images.githubusercontent.com/47725430/159565405-a2b3d2e2-62c7-403c-b83d-9f154f0e83e1.jpg)
Just a thought, as it will help with diagnosing this can you make up a card like this with all the template values listed and screenshot when the erant behaviour is occurring?

**Comment by neildsb** [comment]
will do, good to go, unfortunately will have to wait until 4pm again that's when Tesla trigger the battery dump in the UK

![image](https://user-images.githubusercontent.com/91122872/159574573-0966936b-800e-497d-a671-039b59e06f65.png)

**Comment by Avatar1976** [comment]
Found the solar issue, it's effectively just putting anything (literally anything) going outward the grid on that solar to grid flow.
![image](https://user-images.githubusercontent.com/47725430/159599296-02790c37-58cb-439d-9683-0d22e0794cb5.png)
Seems easy enough to fix, will try and do something rough about it in the next hour or so.

**Comment by Avatar1976** [comment]
> will do, good to go, unfortunately will have to wait until 4pm again, that's when Tesla trigger the battery dump to the grid in the UK
> 


Thanks for your help @neildsb I think @reptilex did a great job on this, my partner actually prefers this over the official Tesla app, would be good to get it working every bit as good as the Tesla app was before they tried to make it all 3D and useless.

**Comment by neildsb** [comment]
here we go, there is about a 3-4 hr window until the battery is empty....

![image](https://user-images.githubusercontent.com/91122872/159742840-bd2402c3-a795-4b54-80b7-7d16bd063948.png)

**Comment by Avatar1976** [comment]
> 

Great data thanks NeilsDB and has given me plenty to consider, I had been wondering how the solar would play into the flows, have been mulling it over all night how I determine what the TEG is sending to grid vs to house house for solar + battery combined output for much of the evening.

**Comment by reptilex** [comment]
With which configuration should I update the documentation?
