### ISSUE TITLE
Battery Icon

### ISSUE THREAD

**Issue by davidfhudson** [reptilex/tesla-style-solar-power-card#11]
Is it possible to change the battery icon based on battery percentage? Very minor feature of course but would make a nice visual guide when glancing at it. Same maybe to change car color based on charge level or something like it (eg green when above 80 or red when below 20).

**Comment by reptilex** [comment]
I have made the changes. I actually wanted to do this and then I forgot, so thank you. I have not thoroughly tested so I should probably call this version beta. If you manage to do so it would be a great help.

**Comment by davidfhudson** [comment]
Working great with two cars. Thank you! 

On Oct 31, 2020, at 2:59 PM, reptilex <notifications@github.com> wrote:

﻿
I have made the changes. I actually wanted to do this and then I forgot, so thank you. I have not thoroughly tested so I should probably call this version beta. If you manage to do so it would be a great help.

**Comment by davidfhudson** [comment]
awesome. works great on a test from full to empty this afternoon. thank you!

**Comment by reptilex** [comment]
I corrected the icon for batteries under 4% but normally this does not happen.
