### ISSUE TITLE
Feature Request:  Adjustable flow speed

### ISSUE THREAD

**Issue by gadgetbazza** [reptilex/tesla-style-solar-power-card#110]
Hi,

Firstly, let me say, love this card and I have just implemented it in my HA.

I do have a rather large solar installation here though, 25kW and I'm also a high energy user with a 3 phase power supply running ground source electric heating and EV car charging.

The card is working brilliantly, the only issue I have with it is that because of my elevated usage numbers, the flow icons are moving very rapidly on the diagram. When the sun shines brightest the line between solar and grid just becomes a blur of movement for me!!!

Is it possible to add a parameter for flow speed factor that the user can configure to apply a factor to the speeds you have inbuilt in the code for the energy animation?  This way a high usage implementation such as mine can be slowed down and perhaps a really low usage one could be sped up (ie if monitoring small components rather than a normal house / solar / grid setup).

Thanks again

**Comment by reptilex** [comment]
you are in luck, I had some free time and had this almost finished, is in new release
