### ISSUE TITLE
Garage: Car "appliance" as independent element, decoupled from house

### ISSUE THREAD

**Issue by ThomDietrich** [reptilex/tesla-style-solar-power-card#113]
Hello,
I understand where the idea to place the car behind the house comes from

![image](https://user-images.githubusercontent.com/2870104/161449989-b72e92b4-54fd-495f-a916-8dca47ed0b9d.png)

However, would it be an option to place the car right next to the house in a "Garage"? I know exactly where the power for my car comes from (pv/battery/grid) and the current visualization shadows the consumption of other household consumers I would like to not forget about...

Thanks and all the best!

**Comment by reptilex** [comment]
I have added the possibility to subtract the value of the appliances from the house bubble. The flows though will stay bound to the house, since most users have entities bound to their solar converters and because changing the flow lines is a real struggle. Check the documentation on the latest release

**Comment by ThomDietrich** [comment]
> because changing the flow lines is a real struggle

Sad to see this ticket shot down immediately. Of course I understand the argument! Thanks for considering anyhow.

Food for thought: If this is implemented: https://github.com/reptilex/tesla-style-solar-power-card/issues/82 I can give the "house" another symbol to represent the "distribution", then I can define one appliance for the car, another one for the heating system, a third for the washing machine, and the forth will be the remaining house consumption.
Jup that would solve my request.

**Comment by ThomDietrich** [comment]
It works!

![image](https://user-images.githubusercontent.com/2870104/161552330-6ac62c73-142e-4338-bf4f-a52eccae8c6e.png)
