### ISSUE TITLE
No dot for solar consumption

### ISSUE THREAD

**Issue by PierreScerri** [reptilex/tesla-style-solar-power-card#12]
![Screenshot 2020-11-16 at 13 19 29](https://user-images.githubusercontent.com/34303331/99251917-6b502600-280e-11eb-89b5-7012e58ee96f.png)
![Screenshot 2020-11-16 at 13 25 12](https://user-images.githubusercontent.com/34303331/99252487-5627c700-280f-11eb-8dbd-066c68573f6d.png)

How many dots should be visible?

**Comment by reptilex** [comment]
That is very strange and most probably a bug, you should see 2 and on the top the dot should be moving faster than the blue one. Did you maybe misspell your "solar_consumption" entity? Or have it somehow mangled up?

**Comment by PierreScerri** [comment]
I  have just checked it again and 2 dots are now visible, as it should be.  Indeed very strange.
![Screenshot 2020-11-16 at 13 49 24](https://user-images.githubusercontent.com/34303331/99254389-950b4c00-2812-11eb-9071-af683146370c.png)

**Comment by reptilex** [comment]
Two dots is normal. At least if you can sell your solar power to your power supplier. But your error was when you had grid_consumption > 0 and solar_consumption > 0 if that happens again let me know.

**Comment by PierreScerri** [comment]
I need to be sure to understand what each entity is.  So correct me if I'm wrong:

grid_consumption_entity: power from grid to house
grid_feed_in_entity: power from solar to grid
house_consumption_entity: power to house
solar_consumption_entity: power from solar to house
solar_yield_entity: power from solar

Behaviour seems to be erratic.

**Comment by reptilex** [comment]
All good house_consumption is more or less the sum of solar_consumption and grid_consumption (and if available battery_consumption). And yes you are correct. grid_feed_in, solar_consumption and solar_consumption are controlling the dots. Maybe you want to control the entities you feed those with in the developer tools, to make sure your entities have the correct data.

**Comment by PierreScerri** [comment]
OK  The sun is gone here so I can't troubleshoot until tomorrow.

Out of curiosity,  why are 5 entities required when 3 would suffice?
What I mean is:  If you have grid_consumption, grid_feed_in and solar_yield, for example, the other 2 can be calculated easily.  It works with other combinations too.

I say this because I have another 'Power-wheel' card. (https://github.com/gurbyz/power-wheel-card) which is also quite cool and that card works everything out from those 3 entities.

Don't get me wrong.  I really like your card.   For the moment I'll keep both and see how it goes.

**Comment by reptilex** [comment]
Well you are almost right. The thing is that there are losses in between in the converter that my converter shows in that form: by having 5 numbers that can differ, i.e. solar_yield is normaly 3-8% higher than solar_consumption + grid_feed_in. But if your inverter does not show this you can use it as a sum through template_sensors.

**Comment by PierreScerri** [comment]
Oh I see.

I see that difference too, but my grid and solar utility meters are both in the same place in the basement.  The inverters are on the roof several meters away.  So the meter for the solar panels is measuring after the losses. ie what is actually delivered to house and grid. So in my case solar_yield is effectively solar_consumption + grid_feed_in.  What is lost is lost.

**Comment by reptilex** [comment]
I have not been able to replicate your issue. I have no erratic behaviour of the dots. Have you been able to test your sensors when you saw the erratic behaviour, if so can you tell me what kind of values they were having?

**Comment by PierreScerri** [comment]
Iwill as soon as the sun comes out.  It's all rainy and grey today.

**Comment by reptilex** [comment]
I guess this has been solved?

**Comment by PierreScerri** [comment]
Yes. Sorry. Seems to be working fine. Thank you.
