### ISSUE TITLE
Line deleted

### ISSUE THREAD

**Issue by gohigher14** [reptilex/tesla-style-solar-power-card#131]
I've deleted the line house_consumption_entity: sensor.house_consumption.
And still the value of house consumption is there in the house balloon.
How can this be?
![image](https://user-images.githubusercontent.com/61975081/192593229-664c92a2-958b-471e-8ceb-2a3b9600b177.png)

**Comment by reptilex** [comment]
shift reload. HA is not as responsive as you might think ;)
