### ISSUE TITLE
Document sensor expectations

### ISSUE THREAD

**Issue by StarfightLP** [reptilex/tesla-style-solar-power-card#14]
I wanted to try this card as it looks really cool but I ran into some problems which can be solved and more importantly be prevented in the future by adding a bit of documentation to each sensor in the usage section of ```README.md```:

1. What measurement is wanted? Some terms can be a bit ambiguous in some setups and a little more explanation can also help with an international community. Examples: momentary power consumed by house, accumulated energy consumption since midnight, battery state of charge
2. What unit is expected? This also helps with 1. Examples: W, kWh, %
3. How are negative values interpreted? This isn't really a problem since you have split up feed and draw but you could state how negative values are treated in general as this can help with debugging. Examples: negative values are clamped to 0

Thanks for creating this very cool card.

**Comment by reptilex** [comment]
I added some comments in the second part and a few more sentences. Do you think that is enough?

**Comment by reptilex** [comment]
I have added details, no answer so I would guess it suffices
