### ISSUE TITLE
Card overlaying top navigation bar

### ISSUE THREAD

**Issue by Remko76** [reptilex/tesla-style-solar-power-card#155]
Ever since the HASS update to 2023.5 I see a strange behaviour with this card. It now overlays the topbar (and thew sidebar depending on your setup). It happens on all browsers and platforms. See this screenshot:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/75678314/236611010-ea22e678-8eca-4bcb-bfdd-ac343e9d49b8.png">

Anyone any idea on the cause and potential fix?

**Comment by reptilex** [comment]
I can confirm this and I know the reason, I will try to solve it very soon.

**Comment by Remko76** [comment]
Cool, sounds promising!! I am interested in the reason, since I have another card showing the same issue, but the developer is not active anymore. So I will need to try to fix that myself…

**Comment by reptilex** [comment]
The reason is they changed something in homeassistant that is using the css z-index on the home menu bar. Since I was using z-index for these two element too that means that  now my z-index meant I go over theirs. I'm having issues building the card, but as soon as I have done that I will post a new version.

**Comment by Remko76** [comment]
I see z-Index being used in my other cars as well. It is this one:
https://github.com/r-renato/ha-card-weather-conditions
unfortunately I have no clue about css. I am afraid it will not be as simple as just changing the value locally..?
Any tips would be appreciated…
Maybe your fix will point me somewhere.
