### ISSUE TITLE
Option to swap car for another icon?

### ISSUE THREAD

**Issue by mattlivermore** [reptilex/tesla-style-solar-power-card#17]
Hi, Loving the card. Got it working very well, thank you.

I don't yet have an EV. But I do have an Eddi immersion boost. Would it be possible to swap the 'CAR' icon for say, a shower head or something similar to visualise my immersion heating?

Thanks,
Matt

**Comment by mattlivermore** [comment]
Well, I think I might have managed this by myself! Edited the .js file, found "mdi:car-sports" and changed to mdi:'shower'. This shouldn't cause any issues until an update right?

**Comment by pman07** [comment]
> Well, I think I might have managed this by myself! Edited the .js file, found "mdi:car-sports" and changed to mdi:'shower'. This shouldn't cause any issues until an update right?
> 
> EDIT: No, that didn't work... :D

That should work, restart HA and clear cache. Although mdi:'shower' should just be mdi:shower.

I just did this to change mdi:solar-panel-large to mdi:solar-power 😄

**Comment by mattlivermore** [comment]
![Untitled](https://user-images.githubusercontent.com/59181997/100282378-63f1f080-2f63-11eb-9c13-f99eaa689e3b.jpg)

Well this doesn't make any sense then.. Restarted, cleared cache, used different browser... All I get is a damn car! Am I editing the right file?  /HomeAssistant/www/community/tesla-style-solar-power-card/ ? Or should I be looking elsewhere...?

**Comment by reptilex** [comment]
So for anyone interested on line 135 of the js file you have to change the mdi:car-sports for any mdi icon you want. Check the icons from https://materialdesignicons.com/ and prefix it with "mdi:"
