### ISSUE TITLE
2024.6.0 appears to have broken visual alignment

### ISSUE THREAD

**Issue by Avatar1976** [reptilex/tesla-style-solar-power-card#173]
Hi,
It would appear that 2024.6 has created some issue with alignment of text within the bubbles.
My card config:
```
type: custom:tesla-style-solar-power-card
house_entity: sensor.powerwall_load_now
grid_entity: sensor.tesla_card_grid_consumption
battery_entity: sensor.tesla_card_battery_consumption
generation_entity: sensor.powerwall_solar_now
generation_to_grid_entity: sensor.tesla_card_grid_feed_in
generation_to_house_entity: sensor.tesla_card_solar_consumption
generation_to_battery_entity: sensor.tesla_card_battery_charging_inside
battery_to_house_entity: sensor.tesla_card_battery_consumption
grid_to_house_entity: sensor.tesla_card_grid_consumption
grid_to_battery_entity: sensor.tesla_card_battery_charging_outside
battery_to_grid_entity: sensor.tesla_card_battery_export
battery_extra_entity: sensor.useable_percentage_remaining
appliance1_icon: mdi:car-sports
appliance1_consumption_entity: sensor.tessytoo_charger_power
appliance1_extra_entity: sensor.tessytoo_battery
appliance2_icon: mdi:fruit-cherries
appliance2_consumption_entity: sensor.cherry_charger_power
appliance2_extra_entity: sensor.cherry_battery
hide_inactive_lines: 1

```

![Screenshot_20240607_083033_Home Assistant](https://github.com/reptilex/tesla-style-solar-power-card/assets/47725430/34d52c8d-7f79-4a72-88be-f8d1b5060530)

**Comment by Avatar1976** [comment]
Page reloads or restarting the home assistant app doesn't seem to make any difference.

**Comment by nigels0** [comment]
I'm finding that the card is a lot smaller than it used to be with this core update.

**Comment by bpuga** [comment]
the cards were considerably reduced, and the text is almost unreadable with the latest HA update. This visualization is used daily in my solar energy system... please correct.

**Comment by reptilex** [comment]
I updated today to test it and saw no issues. But it seems docker stable points to 2024.1.2 strangely enough. I will try to get to this this week. But I have little time. Sorry.

**Comment by bpuga** [comment]
Thank you.


Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by guntherd** [comment]
I can confirm! Since update to 2024.6 the custom:tesla-style-solar-power-card is no longer readable. See screenshot
<img width="1023" alt="image" src="https://github.com/reptilex/tesla-style-solar-power-card/assets/5745355/5918fdce-0f3d-4247-8440-125b61e0e9fb">

**Comment by reptilex** [comment]
Update from hacs. Made a correction since HA cards seem not to have a width attribute anymore.

**Comment by bpuga** [comment]
Work perfect. thank you

**Comment by bpuga** [comment]
perfect work for me... updating from HACS

**Comment by guntherd** [comment]
> I can confirm! Since update to 2024.6 the custom:tesla-style-solar-power-card is no longer readable. See screenshot <img alt="image" width="1023" src="https://private-user-images.githubusercontent.com/5745355/338729843-5918fdce-0f3d-4247-8440-125b61e0e9fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTgzOTksIm5iZiI6MTcxOTI1ODA5OSwicGF0aCI6Ii81NzQ1MzU1LzMzODcyOTg0My01OTE4ZmRjZS0wZjNkLTQyNDctODQ0MC0xMjViNjFlMGU5ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTk0MTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTUzYzM3ZjQwMWNjYjcyODY2YjYwZDg0NTMyYzJlN2I2OTQ1ODdmMDU5NjgzODliZDA5N2Q1MTc3MTNkYWI1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BCQO56whYqQFbvFeqaERT9M6DkpJcBJXjnYJLt4HWIQ">

Unfortunately no change for me after HACS based update, with this simple configuration:
```
type: custom:tesla-style-solar-power-card
name: Home Energy Flow
grid_to_house_entity: sensor.solar_grid_to_house_w
generation_to_grid_entity: sensor.solar_panel_to_grid_w
generation_to_battery_entity: sensor.solar_panel_to_battery_w
generation_to_house_entity: sensor.solar_panel_to_house_w
battery_to_house_entity: sensor.solar_battery_to_house_w
grid_to_battery_entity: sensor.solar_grid_to_battery_w
battery_extra_entity: sensor.solaredge_modbus_battery1_state_of_charge
```

**Comment by bpuga** [comment]
I selected  "Download again".  No work with "Update Information"; only with Redownload.

**Comment by guntherd** [comment]
@bpuga, many thanks for the hint  and many thanks for the fix @reptilex. Now it works for me, too!
