### ISSUE TITLE
2024.6.1 scaling after update 

### ISSUE THREAD

**Issue by csc-solution** [reptilex/tesla-style-solar-power-card#174]
Hi,

after updating to HomeAssistant Core 2024.6.1 the cars-scaling is very small, so it's very difficult to read it on lovelace UI.

Thanks in advance

![grafik](https://github.com/reptilex/tesla-style-solar-power-card/assets/51422947/186fe3ac-96ea-4d59-ae49-36fabb629fc4)

**Comment by keeperlink** [comment]
![image](https://github.com/reptilex/tesla-style-solar-power-card/assets/1500085/faac711b-b097-426f-854a-f7907108be12)
I'm pretty sure it's version 2024.6.0 that broke the view

**Comment by cafarre** [comment]
Same Issue with HA 2024.6.2 version
![image](https://github.com/reptilex/tesla-style-solar-power-card/assets/15473456/73e86594-6714-4438-8cec-660677bae532)

**Comment by poldim** [comment]
Same:
![image](https://github.com/reptilex/tesla-style-solar-power-card/assets/16869713/58ee96e8-37ce-4e4c-9d9d-b1a7218593ff)

**Comment by OneScuzzie2k** [comment]
Following.

**Comment by reptilex** [comment]
No, the issue was that HA changed it's object. There was no card width anymore so I had to retrieve it differently. Just update from hacs or use the latest js file and you should be fine
