### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by dgomes** [reptilex/tesla-style-solar-power-card#19]
Should be possible to have W or kW depending if the value is > ou < then 1000W

Currently W are converted to kW, which is a shame for us with less then 1000W solar panels installed

**Comment by msim888** [comment]
+1

**Comment by reptilex** [comment]
I think I got this covert now. Fresh from the oven, define use_w_not_kw in your yml configuration like this:
`use_w_not_kw: 1`
and you will have w instead of kw and it will not be divided by 1000. Your sensors do have to have the w unit though.

**Comment by dgomes** [comment]
I think I did not made myself clear:

- its not W vs kW
- its W if power < 1000 and kW if power > 1000

**Comment by reptilex** [comment]
won't this look funny when you have 30W solar power and you are using 2 kW? It would confuse the heck out of me. The change is just adding a var to the if statement but I find it's not user friendly that way.

**Comment by dgomes** [comment]
Therefore the importance of showing the unit. 

This is very common in various energy monitor interfaces.

But again, this can be a configuration variable.

**Comment by msim888** [comment]
show_w_not_kw: 1 works very well but there is a problem with speed of cycles - it's too high when show_w_not_kw: 1

 I guess the code should be something like this:

`  getSpeed(value) {
    var speed = 0;
    if (value > 0 && this.w_or_kw !== 'W') {
      speed = 0.07 * value;
    } else if (value > 0 && this.w_or_kw === 'W') {
      speed = 0.00007 * value;
    }
    return speed;
  }`

**Comment by msim888** [comment]
With the code above the speed is normal and everything looks good.
But I have some negative power values - I can use Math.abs() method of course but would be very good to have that option as config option. I mean the option to use negative power values.

**Comment by reptilex** [comment]
Your unreal "pull request" has been merged ;) Do you need a new release to test it? After that I would close the issue and create a new release

**Comment by msim888** [comment]
Sorry, I'm not very good familiar with development process and github. Maybe a new release will be better. Thanks!
