### ISSUE TITLE
Clickable Entities

### ISSUE THREAD

**Issue by tiaanv** [reptilex/tesla-style-solar-power-card#21]
Enhancement request/Suggestion:

Make Entities clickable. If you click on Solar/Grid/Load/Battery etc.  it shows the entity detail graph.

This is in line with most Lovelace card entities.

**Comment by reptilex** [comment]
That's a feature I really want to add. Sadly I'm getting overloaded by the events binding that has to be done. So if you know of any good custom card done in js that has this let me know. I might learn enough to implement it. It actually should not be that hard but I can't seem to get my head around it.

**Comment by tiaanv** [comment]
The one I've been using until I found yours:
[PowerWheelCard](https://github.com/gurbyz/power-wheel-card)

It is responsive, have a look. It's also available through HACS.

**Comment by PierreScerri** [comment]
I've got both in my setup for now.  Can't make up my mind yet.
Clickable entities would be nice.  
PowerWheelCard only responds to clicking the Solar entity, not the other two since these are calculated values not entities.

**Comment by tiaanv** [comment]
> I've got both in my setup for now. Can't make up my mind yet.
> Clickable entities would be nice.
> PowerWheelCard only responds to clicking the Solar entity, not the other two since these are calculated values not entities.

The only one not "click able" in mine is the load(house).  I guess it depends on how it's set up.  The grid, as well as battery are entities. 

With this card it could be more difficuilt, as each block has a seperate consume/feed entity.

**Comment by schwarzenbergf** [comment]
The [button-card](https://github.com/custom-cards/button-card) is a custom card which uses 'tap-action'.
Maybe this helps. I would also love to see tap-action options for every 'circle'.

Anyway, this is 'nice-to-have'. Many thanks for this card, this is what I was waiting for (I'm a Tesla owner).

**Comment by reptilex** [comment]
done in upcoming version, hope to get it online in the next two weeks

**Comment by reptilex** [comment]
Done in Beta. Checkout either the beta release, maybe it's already available through HACS, otherwise either as a release or from the git branch beta1.1. As soon as a few people test this it will become the main branch.

**Comment by schwarzenbergf** [comment]
I tried this. Here is what I did:

- saved "tesla-style-solar-power-card.js" from beta1.1 to the tesla-style-solar-power-card folder while renaming it to "tesla-style-solar-power-card-b11.js"
- changed that name in lovelace/resources in the configuration.yaml
- cleared cache, reloaded resources and reloaded the page again

What I found: 
I can click the circles and get the 'more-info' graph. This works.
But I see now just three almost meaningless circles, all with '0' values.
Do I have to change something in the configuration or is there something more which I have to copy over?

I'll attach the pictures (before/after), hope this helps.
![image](https://user-images.githubusercontent.com/52888262/111077853-00300b00-84f3-11eb-9c16-e2d6210312ac.png)

![image](https://user-images.githubusercontent.com/52888262/111077867-0de59080-84f3-11eb-9cf0-b460feba1621.png)

**Comment by reptilex** [comment]
Sorry, I forgot to say that the configuration has changed and will probably change once more when beta is released for real. 
You need an entity for each bubble and an entity for each line. Checkout the beta Readme.

**Comment by schwarzenbergf** [comment]
OK, I used now your new configuration and I see the bubbles as expected.
But the values shown in the bubbles does not match my expectations anymore.
I played around with this for some hours but especially for the PV bubble I could not get any meaningful value to be shown.
I understood that your are computing most values in the bubbles now (but I do not understand why ? ).
I have 4 main sensor values from my system (Victron Energy ESS):

1. PV Power
2. Grid Power (+/-)
3. House Load
4. Bat Power (+/-)

And those sensor values I would like to see in the bubbles.
The simplest way would be just to show them without any computation.
But I guess there is a reason why you changed this.
So, could you show me a way how to get this back. How should your 'flow entities' look like to get back this behavior?

BTW, it worked very good for me with the old version. The animation in your card is really good and was the reason for me to drop Power-Wheel-Card. I'm not interested in detailed numbers of the flow (how much energy flows from here to there), this shows the animation much better - but this is just my opinion.

**Comment by reptilex** [comment]
Sorry to hear you are having problems. The reason I changed the bubble values, was because a lot of people requested flow values which were not being updated in the bubbles. Like battery_to_grid, this is not what used to be battery_consumption, which was the value of the bubble.
so I would guess that your configuration needs:
a) generation_to_house_entity= 1.PV Power
b) grid_to_house_entity=2a. Grid Power +
c) generation_to_grid_entity=2b.Grid Power -
d) battery_to_house_entity=4b Bat Power -
e) generation_to_battery=4a Bat Power +

House load should not be needed or only as a click entity for house_entity (optional) If you still have problems just let me know. The feature request is implemented by the bubble click entities as described in the readme.
