### ISSUE TITLE
To many routes for the power.....

### ISSUE THREAD

**Issue by B-Hartley** [reptilex/tesla-style-solar-power-card#22]
Hi,

In my setup, I have.....

Grid
Solar
Battery
Car1
Car2

But The battery can charge from the grid or from solar.
Solar could go to the battery, to the car, to the grid.

It's too complex to work out what is going where.

The only way I could do it really would be to just have a star with a central hub.
Each device (battery, solar, house, car etc.) is a spoke on the wheel and gives or receives power.

This is how myEnergi show it in their app and it makes sense.
For me to calculate sensors for solar to house, solar to grid, solar to battery would be too complex.

It's a shame, as I like the presentation of your card, but I can't make it work in my setup.

Thanks anyway.

**Comment by reptilex** [comment]
well if you place the car behind the home you can deal with your problem rather easily. How I would use it with this card would be:

1. Create a new sensor that sums car battery + car battery2 + home usage = home_consumption_entit

**Comment by reptilex** [comment]
Another thing to keep in mind is that you might be having sensors with negative values, you just need to create template sensors with positive values that are for other stuff. Say positive value on the battery loads it and negative value unloads it. With a template sensor like the one I describe in the readme you should be able to divide these kind of sensors.

**Comment by B-Hartley** [comment]
I'll have another go at juggling the sensors and post back how I get it done.
