### ISSUE TITLE
Double lines when loading from grid.

### ISSUE THREAD

**Issue by reptilex** [reptilex/tesla-style-solar-power-card#24]
As @msim888 reported, when you have power from grid, the power lines for charging battery are also being shown and have a moving circle. So I'm trying to get to the bottom of this

**Comment by reptilex** [comment]
![101820403-3eeaa980-3b2f-11eb-82b3-fdc3266e63b2](https://user-images.githubusercontent.com/8057797/101880480-45ab0800-3b93-11eb-8fdd-914402cb0d33.png)

**Comment by reptilex** [comment]
So what I have figured out is that since I never started up with the idea of charging from other than solar I made the line from solar to battery the "battery_charging" entity. This should be better called, "battery_from_solar". Could it be that this sensor is not 0 when you are having "grid_to_battery"? If this is the case your "battery_charging" entity should only have values when charging from solar (maybe you create a template and subtract from it "grid_to_battery".

However if this is not the case I would need to dig in further. Maybe you can give me the values of your entities when the error happens?

**Comment by msim888** [comment]
Below is my card configuration:

`house_consumption_entity: sensor.victron_home_ac_consumption
grid_consumption_entity: sensor.victron_home_grid_out
grid_feed_in_entity: sensor.victron_home_grid_in
solar_consumption_entity: sensor.victron_top_pv_power
solar_yield_entity: sensor.victron_home_pv_power
grid_to_battery_entity: sensor.victron_home_grid
battery_charge_entity: sensor.victron_home_battery_soc
battery_charging_entity: sensor.victron_home_battery_power_in
battery_consumption_entity: sensor.victron_home_battery_power_out
show_w_not_kw: 1
hide_inactive_lines: 1`

**Comment by msim888** [comment]
Actually this isn't a big problem but maybe it's better to fix it (if it's possible of course).

**Comment by reptilex** [comment]
Ok. I understand both:
solar_consumption_entity: sensor.victron_top_pv_power
solar_yield_entity: sensor.victron_home_pv_power
where 0. But that would not affect that line.

The question is whether sensor.victron_home_battery_power_in is also 0
So the line going from PV to the battery is handled by the battery_charging_entity. This entity should only contain solar energy being directed from your panels/inverter to your battery. And not counting in all the energy the battery is receiving. Like I said, the name is misleading. It should be called battery_charging_from_pv

**Comment by msim888** [comment]
Oh, I understand. Unfortunately I haven' sensor which indicates only the solar to battery energy.

**Comment by reptilex** [comment]
Well this can be probably be calculated like
battery_charging_from_pv = sensor.victron_home_pv_power - sensor.victron_top_pv_power 
or with your sensor.victron_home_battery_power_in
sensor.victron_home_battery_power_in - sensor.victron_home_grid
or a combination of the two
check out 
https://www.home-assistant.io/integrations/template/
You can test those in your developer tools->Template 
There you can also find some examples

**Comment by msim888** [comment]
Great! Thanks, reptilex!
