### ISSUE TITLE
the home consumption is not show the value

### ISSUE THREAD

**Issue by JPOliveGit** [reptilex/tesla-style-solar-power-card#25]
house_consumption_entity: sensor.smatiototalhome
grid_consumption_entity: sensor.smartiofromgrid
grid_feed_in_entity: sensor.smartiotogrid
solar_consumption_entity: sensor.smartiosolarhome
solar_yield_entity: sensor.shellyem_c7fad6_channel_2_power
type: 'custom:tesla-style-solar-power-card'

just showing NAN kW why if every sensor has values and how can I make it show in W not kW? Thanks

**Comment by reptilex** [comment]
Your have misspelled your house consumption sensor: "sensor.smartiototalhome" and not  "sensor.smatiototalhome" (missing r)
And to show Watt instead of kW you have to use:
```yml
show_w_not_kw: 1
```
As stated in the readme: https://github.com/reptilex/tesla-style-solar-power-card
