### ISSUE TITLE
Title needed

### ISSUE THREAD

**Issue by chheiss** [reptilex/tesla-style-solar-power-card#28]
It would be great if one could set a title in the card config to show a title. Is that possible?
So if I have two such cards and two solar systems, I could name both.

**Comment by reptilex** [comment]
Will add this in the upcoming reworked version.

**Comment by reptilex** [comment]
Done in Beta. Checkout either the beta release, maybe it's already available through HACS, otherwise either as a release or from the git branch beta1.1. As soon as a few people test this it will become the main branch.

**Comment by reptilex** [comment]
Works in the newest release. Beware of the configuration changes, read the Readme.md before updating!
