### ISSUE TITLE
Car2 doesn't show properly

### ISSUE THREAD

**Issue by dgomes** [reptilex/tesla-style-solar-power-card#29]
Unless a battery is defined, car2 does not show properly

<img width="487" alt="Screenshot 2020-12-26 at 15 22 30" src="https://user-images.githubusercontent.com/137684/103154268-2d8bd900-478e-11eb-88e2-066a6b703db4.png">

PS: I've been opening PR, but this point I really need help ;)

**Comment by reptilex** [comment]
Try the new LitElement Branch. But you will need to redefine the configuration and I'm having trouble with the config editor. And this does not have your changes yet. Hope to get them up in the coming days.

**Comment by reptilex** [comment]
But just as a test, there are a few bugs there still. It's worth looking at it. It's a bit neater.

**Comment by reptilex** [comment]
This only works with a battery currently. Will work flawlessly in upcoming beta.
