### ISSUE TITLE
Show up in card picker

### ISSUE THREAD

**Issue by KTibow** [reptilex/tesla-style-solar-power-card#30]
Cards can show up in the card picker using this syntax:
```
window.customCards = window.customCards || [];
window.customCards.push({
  type: "content-card-example",
  name: "Content Card",
  preview: false, // Optional - defaults to false
  description: "A custom card made by me!" // Optional
});
```
It'd be nice if this card supported that.

**Comment by reptilex** [comment]
is also in the next version, hopefully online next week, will need a new setup for the card

**Comment by reptilex** [comment]
Done in Beta, but not with visual editor. Checkout either the beta release, maybe it's already available through HACS, otherwise either as a release or from the git branch beta1.1. As soon as a few people test this it will become the main branch.

**Comment by reptilex** [comment]
Done in new release. Beware of breaking config changes. Read the Readme.md
