### ISSUE TITLE
car consumption problem or new feature

### ISSUE THREAD

**Issue by JPOliveGit** [reptilex/tesla-style-solar-power-card#31]
i was trying to use the car consumption but not for a car, for a solar water heater, it has a resistance that can be turned on and  when it on it has a consumption. when I integrated it with this card it shows a little bit weird I think because the card is not prepared to show only the consumption everything misaligned, please make it possible to have or not the % to everything be aligned perfectly

**Comment by reptilex** [comment]
this is implemented in my next version, finishing it up hopefully this week, corona has me busy at home

**Comment by reptilex** [comment]
Done in Beta. Checkout either the beta release, maybe it's already available through HACS, otherwise either as a release or from the git branch beta1.1. As soon as a few people test this it will become the main branch.

**Comment by JPOliveGit** [comment]
thks for the fast reply this is what this community has to do! help making thing better

**Comment by reptilex** [comment]
Ok, so far I have only been able to get the error you are showing when one of the entities does not exist. So if you have misspelled your sensor. Could you check? I'm still on it but that might be the error on your side.

**Comment by JPOliveGit** [comment]
grid_consumption_entity: sensor.smartiofromgrid
house_consumption_entity: sensor.smartiohome
generation_yield_entity: sensor.smartiosolarhome
appliance1_consumption_entity: sensor.shelly_shsw_pm_68c63afae821_current_consumption
generation_to_house_entity: sensor.shelly_shem_c7fad6_2_current_consumption_2
generation_to_grid_entity: sensor.smartiotogrid
grid_to_house_entity: sensor.smartiofromgrid
type: 'custom:tesla-style-solar-power-card'

now is correct but it still doesn't show nothing

<img width="734" alt="Captura de ecrã 2021-03-10, às 20 25 39" src="https://user-images.githubusercontent.com/13860407/110692942-d15a2200-81de-11eb-8cce-19fbc3e724e7.png">

**Comment by JPOliveGit** [comment]
can you share the manual with all the changes from this version?

**Comment by JPOliveGit** [comment]
hey Reptilex I found the problem every time I insert "appliance1_consumption_entity: " all disappear if I remove it from the config it shows solar grid and home there's something about appliance1_consumption_entity

**Comment by JPOliveGit** [comment]
Reptilex i made it from a fresh start and now it works, how can i change the icon from the car to and appliance? and if you see in the image the line isn't in the right position... but it's working now

<img width="520" alt="Captura de ecrã 2021-03-11, às 12 13 11" src="https://user-images.githubusercontent.com/13860407/110785713-2b9cc680-8263-11eb-8b99-ab00b6f97cf7.png">

**Comment by reptilex** [comment]
Great! I was still trying to replicate your error without success, good that it works now. To change the appliance icon just add
```yml
appliance1_icon: mdi:air-filter
```
or any icon you find here with 'mdi:' prefixed: https://materialdesignicons.com/ 
And yes, the line is really a headeache, haven't figured out a better way to do that one yet. I think I will have to redo the hole paths and circles part, because it also uses too many hardware resources. Maybe on the 1.2 version. Did not want to take on everything at once.

**Comment by JPOliveGit** [comment]
and what about "show_w_not_kw: 1" is not showing W continues to show kW

**Comment by reptilex** [comment]
Yes I had a bug there, check whether w_not_kw works or download the latest version, there it's corrected and show_w_not_kw is now the correct name.

**Comment by JPOliveGit** [comment]
yes it works with w_not_kw, another supposed bug, the color of the flow of energy it show a dark color almost can't see the flow. In a future update can you make possible to choose the color of the bubbles and flow directly in the UI without editing the JS?

<img width="517" alt="Captura de ecrã 2021-03-11, às 19 31 40" src="https://user-images.githubusercontent.com/13860407/110843631-6e30c400-82a0-11eb-8b19-83bc796209ba.png">

**Comment by reptilex** [comment]
planned. But those colors are supposed to be your theme colors. Strange, it should be the same colour as either the house or the grid. Will have to check. Thank you for the bug report.

**Comment by JPOliveGit** [comment]
in the last update it broke the position of the appliance, if we remove it everything is in the right position if we add it don't

<img width="513" alt="Captura de ecrã 2021-03-26, às 10 49 17" src="https://user-images.githubusercontent.com/13860407/112622233-a8629f80-8e22-11eb-90ec-af43a7c561ca.png">

**Comment by JPOliveGit** [comment]
with the 1.1.5 update it returned to normal but with the same gap of the line in the appliance 

<img width="480" alt="Captura de ecrã 2021-03-27, às 10 14 38" src="https://user-images.githubusercontent.com/13860407/112717555-736b5100-8ee5-11eb-9504-d781496c954b.png">

**Comment by reptilex** [comment]
The gap is still an issue, I will address that with the next iteration. But your feature works now, so I will close this issue.
