### ISSUE TITLE
Add grid_to_battery to grid_consumption in kW display

### ISSUE THREAD

**Issue by MindFreeze** [reptilex/tesla-style-solar-power-card#32]
These 2 have to be exclusive in the config for the animation to be correct. But when displaying grid power kW in the circle, it makes sense to display all the power being pulled from the grid, including what goes to the battery.

**Comment by reptilex** [comment]
This is an issue with your sensors. My sensor does this on it's own so if you are having this issue you might need a template sensor

**Comment by MindFreeze** [comment]
The thing is I often have grid_to_battery but 0 grid_consumption. This is just my use case. I can charge the batteries with the grid being otherwise cut off.
So if do the addition in my sensors, the lines wouldn't make sense.

**Comment by reptilex** [comment]
I think I did not understand your problem in the first place. What is wrong in the display currently? can you tell me your data and maybe post an image? I thought your icon was showing the wrong sum. This could be handled with a third sensor (template sum sensor) for that icon. But it seems I misunderstood

**Comment by MindFreeze** [comment]
https://pasteboard.co/JMdkvef.png
This is what I would get even though I have 1kw going to the battery. It is not calculated in the battery display or the grid display.
If I add that to grid_consumption, it would show proper kW for the grid. But if I my grid_consumption is otherwise 0, it would show a line going to the house which would be wrong.

You are right that the grid part can be handled with a new sensor like `totoal_grid_consumption` similar to `solar_yield`. But that would still leave the battery kW wrong.

**Comment by MindFreeze** [comment]
IMO the new sensor path is redundant and so it the `solar_yield` sensor. After all, it is just `solar_consumption`+`battery_charging`.
If we define the power over all the paths, we can easily calculate the kW that should be displayed in the icons.

**Comment by headbouyJB** [comment]
solar-yield may also include solar that you're exporting, as well as consumption and battery charging. 
I spent far too long trying to work out the logic to calculate the required sensors based on the sensors I have available :-D 

It looks like I have this working so far, the only thing I believe is missing is battery to grid.

**Comment by reptilex** [comment]
Well there is a battery to grid line, and if your consumption shows battery to grid, then you should be having that too.

**Comment by reptilex** [comment]
About the redundancy, you might be right. But I have them because my solar meter shows the actual yield without losses. But I'm thinking whether this should be left out in the next iteration.

**Comment by headbouyJB** [comment]
> Well there is a battery to grid line, and if your consumption shows battery to grid, then you should be having that too.

Ah OK cool! - reading through your list of sensors, there didn't seem to be a battery-to-grid option. 
Can the grid-to-battery be negative then?

**Comment by reptilex** [comment]
Done in beta! But you would need to either checkout the beta branch or at least the binary or try a beta installation through HACS. But it would be a great help if you could test it. As soon as a few people do this is going to become the main branch.

**Comment by headbouyJB** [comment]
OK so I thought I'd give the beta a go via HACS - but I'm not getting anything displayed at all. 
Have restarted, everything is updated, and the badges display the correct values for the sensors I'm attempting to use. 

Is there something simple I'm missing here?

<img width="977" alt="Screen Shot 2021-03-10 at 9 26 22 AM" src="https://user-images.githubusercontent.com/23249268/110607368-08024f00-8183-11eb-819c-4479cd07ecd8.png">
<img width="1160" alt="Screen Shot 2021-03-10 at 9 22 50 AM" src="https://user-images.githubusercontent.com/23249268/110607372-089ae580-8183-11eb-99c2-9bcc82ed575a.png">
<img width="994" alt="Screen Shot 2021-03-10 at 9 22 34 AM" src="https://user-images.githubusercontent.com/23249268/110607374-09337c00-8183-11eb-8e40-b63b2d20df0e.png">
<img width="827" alt="Screen Shot 2021-03-10 at 9 22 16 AM" src="https://user-images.githubusercontent.com/23249268/110607375-09cc1280-8183-11eb-8d33-788af4e0d3d5.png">
<img width="827" alt="Screen Shot 2021-03-10 at 9 22 10 AM" src="https://user-images.githubusercontent.com/23249268/110607377-09cc1280-8183-11eb-81fb-f1cdef5869ba.png">

**Comment by MindFreeze** [comment]
Open dev tools and look for errors in the console. I've never seen this behavior.
It could be a cache problem.

**Comment by headbouyJB** [comment]
I see the same result in Safari and Chrome, even after clearing caches and refreshing. 
My logs only have normal HACS custom component warnings. 

I haven't used the dev tools and console before - is there a quick guide available so I can be helpful please?

Also with the same configuration the card does display in the iOS app, but not all the values are coming in. 
![IMG_1976](https://user-images.githubusercontent.com/23249268/110610060-c2935100-8185-11eb-96f4-476e7a31f19d.jpg)

**Comment by reptilex** [comment]
strange, will do some more testing this evening and get back to you asap

**Comment by reptilex** [comment]
If the problem with the rounding persist, please open a new issue. I tried replicating it, but although sometime I got really long float numbers I never had a 0 problem. The feature request is implemented in latest breaking config release.  ;)
