### ISSUE TITLE
When no Solar is being produced.

### ISSUE THREAD

**Issue by whycali** [reptilex/tesla-style-solar-power-card#34]
I was wondering if there is a way to make the line disappear when there is 0 solar being produced. Right now when it says 0 it still has the line going to the "House" wondering if there is a way to turn it off when no power is being produced?

**Comment by reptilex** [comment]
I think this is only possible in the new version I'm working on. Sorry. Will be ready before march I hope

**Comment by whycali** [comment]
@reptilex Thank you for the replay. Cant wait to see what you have in store for the update.
