### ISSUE TITLE
Can I change the icons on the cars?

### ISSUE THREAD

**Issue by meteosat007** [reptilex/tesla-style-solar-power-card#35]
Hi,

Located my .js and changed the mdi icons but even after restarts they remain as a car.

Also when I auto install on hassio not docker install the card never appears in the +Card option.

Latest versoions of super visor and all.

Just wanted to customise for my install but other than that it works really well....

Location of the .js on my install
/config/www/community/tesla-style-solar-power-card/tesla-style-solar-power-card.js

`
    if(config.car_charging_entity != undefined){
      this.carCharge = new sensorCardData();
      this.carCharge.entity = config.car_charging_entity;
      this.carBatteryState = new sensorCardData();
      this.carBatteryState.entity = config.car_battery_entity;
      this.carIcon = '**mdi:fish**';
    }

    if(config.car2_charging_entity != undefined){
      this.car2Charge = new sensorCardData();
      this.car2Charge.entity = config.car2_charging_entity;
      this.car2BatteryState = new sensorCardData();
      this.car2BatteryState.entity = config.car2_battery_entity;
      this.car2Icon = 'mdi:**computer-classic**';
    }
`

**Comment by reptilex** [comment]
Well actually the icons for the "extra appliances" are only on two places line 145 and line 153. Maybe you haven't restarted and cleared your cash? mdi:fish should work 'mdi:**computer-classic**' looks weird. On mobile you have to clear the cash manually by a button in the menu.
The new version will probably allow to set them on the config. Will take a while though.

**Comment by reptilex** [comment]
Hey, if you are willing to test the newest beta release or chekout the beta branch (there is a "binary" js file also) that would include a variable to change icons. Beware though the configuration has changed a bit.

**Comment by reptilex** [comment]
You can now change every icon with the [bubbleName]_icon variable in the config. Checkout the readme.md. Be aware that the way the configuration works has changed completely.
