### ISSUE TITLE
Default/sample setup for Tesla integration

### ISSUE THREAD

**Issue by vvuk** [reptilex/tesla-style-solar-power-card#37]
It would be nice if there was a documented sample setup for the entities created by the Tesla integration.  Those are:

```
powerwall_battery_now -- kW; negative if powerwall is charging, positive is powerwall is discharging 
powerwall_site_now -- kW; grid access. negative if feeding back to the grid, positive if incoming
powerwall_solar_now -- kW; solar power production
powerwall_load_now -- kW; current home load
```

Also a couple of binary values like `grid_status`.

I don't actually know if it's possible to deduce all the different paths just from this data.  I'll dig in to some of the additional data on each entity's value.  There are some constraints that would help; for example, if solar is installed, powerwall will only charge from solar (_except_ during storm watch events).  But e.g. solar production could be going to house, powerwall, and grid, with the powerwall incoming charge varying based on the powerwall's needs.  I can attempt to work out the right expressions to calculate exactly how much is going to each, but if someone has already done it it would be helpful to have in the readme :)

A small suggestion -- would be nice if the config names followed a pattern to make them easier to reason about in complex expressions.  e.g. currently config wants the first column names; the second might be easier to think about (for me):

| Cur Name | Maybe New Name |
| ----- | ----- |
| solar_consumption_entity | solar_to_house_entity |
| grid_feed_in_entity | solar_to_grid_entity |
| battery_charging_entity | solar_to_battery_entity |
| battery_consumption_entity | battery_to_house_entity |

might make it a little easier to see what's going where.

**Comment by robertfgoodworth** [comment]
Yeah i'm lost too with this card and the Telsa intergration sensors and the sensors this card seems to need.

**Comment by reptilex** [comment]
I have a completely new version that is written in typescript and I have been unable to get it done due to the lockdown. I hope to get to it in march. Your name suggestions are pretty good. I'll adopt them for the new version.
About negative values: Currently I haven't implemented negative values therefore you would need to create template sensors for positive and negative values as separate sensors. Sorry.

**Comment by vvuk** [comment]
Great, looking forward to it!  It's less about negative values, and more about having an out of box setup for people with a tesla install

**Comment by reptilex** [comment]
There is now a documentation on the readme page. Is that enough for now? Maybe it should be added that the battery_to_grid functionality is not there yet and would not show. Apart from that the configuration example looks pretty solid, is there more needed?

**Comment by robertfgoodworth** [comment]
Hi There,

 

THANKYOU so much for adding the how to, it worked perfectly. Love this card, great job.

 

Regards

Rob

**Comment by vvuk** [comment]
Yep, that's great; thank you!
