### ISSUE TITLE
Feature Request: Wind Yield and Consumption

### ISSUE THREAD

**Issue by vongyver** [reptilex/tesla-style-solar-power-card#39]
I have a node-red renewable simulator that also has wind.  Any change you could add wind as a source?

Kudos for starting a new project and sharing.  Thanks!

**Comment by reptilex** [comment]
Well you can use wind instead of solar power and in the latest beta you can also change the icons. Is that enough?

**Comment by vongyver** [comment]
Hi reptilex,

Sorry I missed the first response.  Fair that you closed it.
I have both solar and wind in the calculations, in fact multiple wind
turbines simulated.  Keep doing the great work you have been and I will
monitor.
If there is any way I can help, let me know.

Eric
