### ISSUE TITLE
FEATURE REQUEST: Can the card support two cars ?

### ISSUE THREAD

**Issue by B-Hartley** [reptilex/tesla-style-solar-power-card#4]
This card is exactly what I was looking for.
But is there any chance it could support 2 cars ?

Thanks

**Comment by reptilex** [comment]
I have added the functionality for having two cars but I would call it alpha state. I will not merge it to the master branch until you test it thoroughly ;)
You can get it from the twocars branch here:
https://github.com/reptilex/tesla-style-solar-power-card/tree/twocars
Just copy the js file, replace the one you have in your configuration and you should see another car on top of home. The only "ugly" thing is that the cars svg lines are not part of the big middle svg hence they are not align responsively. Therefore they might overlap on the circles and look unordered. 
Let me know if you find something.

**Comment by B-Hartley** [comment]
Ok. Thanks. I’m a bit ahead of myself really. The solar and powerwall are being installed next week.
I’ll get it setup with the house and the cars and see what happens.
From the docs I’m not 100% sure what you expect each of the sensors to show.
Could you clarify what you expect from each of the sensors shown in your “full config” and what I should call the 2nd car.

Thanks.

Bruce Hartley
Click Spares
07966 924863

________________________________

**Comment by reptilex** [comment]
you can call your cars whatever you want. Mine is actually called that way, hence the sensor name, this was done in the car dashboard and the api sends the name as such. Are you sure you want to leave your full name and number there?

**Comment by B-Hartley** [comment]
Thanks. I’d replied by email without thinking. 
When I Keane what to call the car I meant the parameter name. But I’ve found it in your docs now. 

To make sure I understand the parameters. 

car_charging_entity: kw into car
battery_charge_entity: % battery level powerwall
battery_charging_entity: kw into powerwall
battery_consumption_entity: kw out of powerwall
car_battery_entity: % battery level car
grid_consumption_entity: kw from grid
grid_feed_in_entity: kw to grid 
house_consumption_entity: kw used by house (including cars)
solar_consumption_entity: solar to house ??
solar_yield_entity: solar production

Thanks.

**Comment by reptilex** [comment]
house consumption I use including cars, but you can substract them in a sensor template if you want to. Up to you. solar_consumption is direct consumption from the panels.

**Comment by B-Hartley** [comment]
thanks !
