### ISSUE TITLE
colored icons depending from the consumption

### ISSUE THREAD

**Issue by juuhee84** [reptilex/tesla-style-solar-power-card#40]
Hey guys!

I’m more than happy about this great card! Perfect!

But I still have one more idea:
Is it possible to configure the icons in a way, that e.g. the house is displayed in green if it is only supplied by solar power, in yellow if it is powered by solar power and power from the grid and in red, if only power from the grid is used?

I tried to chande the *.js file in different ways, but I didn’t become it working…
And I am no specialist in programming cards…

Maybe someone can help me?

Maybe it is also possbile to make the colors configurable via tha yaml-data for the card?

Thanks,
Julian

**Comment by reptilex** [comment]
Working on it. Probably be done next week.

**Comment by reptilex** [comment]
For this to work just add the following to your config:
```yml
change_house_bubble_color_with_flow: 1
```
