### ISSUE TITLE
Flow doesn't show up

### ISSUE THREAD

**Issue by ptgomes** [reptilex/tesla-style-solar-power-card#41]
On the previous version, I only had flow from Grid to House, not from solar power to House; on this version no flow whatsoever. What can it be?
Values showned are correct.

![image](https://user-images.githubusercontent.com/31014473/110803802-7cb6b580-8277-11eb-8d59-153213b7c8e7.png)

**Comment by reptilex** [comment]
could you add your configuration? and are you using the new beta?

**Comment by ptgomes** [comment]
After some restarts, the flow between grid and home works. But not solar->Home. Never did even on previous release.
Using latest beta. 

![image](https://user-images.githubusercontent.com/31014473/110818320-0d47c280-8285-11eb-9cf8-32f43f20cf39.png)
```


type: 'custom:tesla-style-solar-power-card'
house_consumption_entity: sensor.consumo
solar_yield_entity: sensor.kostal_pv_power
grid_consumption_entity: sensor.total_energia
show_w_not_kw: 1

```

**Comment by reptilex** [comment]
For the latest beta you need a sensor for every line, I'm amazed that the house to grid works.
Check the beta Readme document here: https://github.com/reptilex/tesla-style-solar-power-card/tree/beta1.1#Usage

**Comment by ptgomes** [comment]
So, even if I dont have those sensors, I must include them ?
With this code nothing appears.
(First three I have)

type: 'custom:tesla-style-solar-power-card'
house_consumption_entity: sensor.consumo
solar_yield_entity: sensor.kostal_pv_power
grid_consumption_entity: sensor.total_energia
show_w_not_kw: 1
generation_icon: 'mdi:solar-power'
name: My Flows
generation_yield_entity: sensor.solar_yield
battery_consumption_entity: sensor.battery_consumption
grid_to_house_entity: sensor.grid_consumption
grid_to_battery_entity: sensor.grid_battery_charge
generation_to_grid_entity: sensor.grid_feed_in
generation_to_battery_entity: sensor.battery_charging
generation_to_house_entity: sensor.solar_consumption
battery_to_house_entity: sensor.battery_consumption
battery_to_grid_entity: sensor.battery_to_grid
battery_extra_entity: sensor.battery_charge
house_extra_entity: sensor.current_temperature
generation_extra_entity: sensor.percent_cloud_coverage
grid_extra_entity: sensor.monthly_feed_in
appliance1_consumption_entity: sensor.car_consumption
appliance1_extra_entity: sensor.car_battery_state_of_charge
appliance2_consumption_entity: sensor.heating_consumption
appliance2_extra_entity: sensor.heating_operation

**Comment by ptgomes** [comment]
Figured it out, need to make sensors for the flows.

Question: on dark theme, the dot of the flow Grid->House is almost invisible; is it possibel to change?

![image](https://user-images.githubusercontent.com/31014473/110935373-3e78cf00-8327-11eb-9f91-378804d668da.png)

**Comment by PierreScerri** [comment]
I have the same issue with the dark theme.  The dot is there but its colour is similar to the background.  Shouldn't it be blue?
I don't know Javascript but I looked at the code and there is no mention of 'grid_to_house_entity_circle'.  Only 'generation_to_...' and 'battery_to...' circles are there.  Or have I got it wrong?

**Comment by reptilex** [comment]
It should actually be white, but I will correct it so that it is blue. Still strange.

**Comment by PierreScerri** [comment]
It is not white. It is a dark grey. Doesn't matter what colour it is as long as it is visible, but if I have a choice it would be the same colour as the line.

![Screenshot 2021-03-19 at 16 08 42](https://user-images.githubusercontent.com/34303331/111802360-2debca00-88ce-11eb-8a0a-67d2f7811a03.png)
![Screenshot 2021-03-19 at 16 09 08](https://user-images.githubusercontent.com/34303331/111802363-2f1cf700-88ce-11eb-97d8-1a7481f2a2c5.png)
