### ISSUE TITLE
Feature request: Watt to kiloWatt threshold

### ISSUE THREAD

**Issue by pascalwinters** [reptilex/tesla-style-solar-power-card#42]
Is it possible to change the setting: show_w_not_kw to an option to show default Watt values and show kiloWatt above an configured threshold?

**Comment by reptilex** [comment]
can be done, but currently I'm working on getting beta 1.2 to production and will probably not get to that in a few months. If you are a dev, you are welcome to checkout beta branch and put in a pull request.

**Comment by pascalwinters** [comment]
> can be done, but currently I'm working on getting beta 1.2 to production and will probably not get to that in a few months. If you are a dev, you are welcome to checkout beta branch and put in a pull request.

Any tips for running/debugging locally?

**Comment by reptilex** [comment]
this feature is actually rather basic, you can just create a new test for the SensorElement that does the calculation and pass  around the configuration variable. If you actually want to test it you can just install the home assistant docker and add hass add the beta and just foll around with sensor of the development tools.

**Comment by reptilex** [comment]
I have published this feature but have not created a new release, so if you checkout the master branch or you just copy the js file in the root to your installation it should work. Maybe you can test it. You can also checkout the new tests in the sensorelement test file.

**Comment by reptilex** [comment]
just made a new release, for the conversion from watt to kilowatt to be done from 5000 whats add 
```yml
threshold_in_k: 5
```
