### ISSUE TITLE
White icons

### ISSUE THREAD

**Issue by PierreScerri** [reptilex/tesla-style-solar-power-card#43]
The picture says it all.

![Screenshot 2021-03-25 at 10 29 35](https://user-images.githubusercontent.com/34303331/112451012-49832480-8d55-11eb-8413-b261e5c8cc70.png)

Running Beta 1.1.4

**Comment by ptgomes** [comment]
Also
![image](https://user-images.githubusercontent.com/31014473/112620900-00000b80-8e21-11eb-9020-291a69ad2efd.png)

**Comment by reptilex** [comment]
Sorry folks, just pushed a new beta release with the fix.

**Comment by ptgomes** [comment]
Thank you!

A sexta, 26/03/2021, 20:28, reptilex ***@***.***> escreveu:

**Comment by PierreScerri** [comment]
Looks good.  Thanks.
