### ISSUE TITLE
Lines and/or entity-icons are placed incorrect

### ISSUE THREAD

**Issue by Kartax** [reptilex/tesla-style-solar-power-card#44]
I noticed, that either the lines or the entity-icons are placed incorrect .
Lines overlap or there is space between them and the entity-icon.

![image](https://user-images.githubusercontent.com/24891257/112732416-1bab0500-8f3a-11eb-939d-4f14cfd3e072.png)

Card Version 9.2.2
HA Version 2021.3.4
I am using the default theme.

**Comment by reptilex** [comment]
the extra entities still suffer from that problem in the release I did a few seconds ago, but most things are better. Beware you need to redefine your configuration according to the Readme.md. Everything has changed.
