### ISSUE TITLE
Typescript Update

### ISSUE THREAD

**Issue by ThePrincelle** [reptilex/tesla-style-solar-power-card#48]
This card is simply amazing. 

Unfortunately, since the last update it doesn't work on Safari or on the iOS app anymore. 

Here's what I can see : 
<img width="486" alt="image" src="https://user-images.githubusercontent.com/52919205/113121658-28b64580-9213-11eb-8a43-d715d54cabfa.png">

I don't see anything about the card in the logs. 

Thanks again.

**Comment by oliversoerensen** [comment]
same to me :-( 
(macOS and iOS)

**Comment by ThePrincelle** [comment]
On iOS, I got it working by into the app, then "App Configuration" then "Delete frontend cache". 
After that, simply refresh the screen after.

**Comment by oliversoerensen** [comment]
Thats works, thanks. 
And Safari on Mac: Menu Developer->Clear Cache  
after that cmd-r  
Voila!

**Comment by ThePrincelle** [comment]
Thanks ! 
Working like a charm.
