### ISSUE TITLE
Line thickness instead of bubbles

### ISSUE THREAD

**Issue by oliversoerensen** [reptilex/tesla-style-solar-power-card#50]
I have an optional feature request:

To make the display smoother, it would be nice to show the energy flow not by the flowing bubbles but by the thickness of the lines. 1 pixel = 1 kW. 
Display Options selectable: Bubbles or thickness.

Also the CPU consumption would be probably smaller thereby.

Like this:
![Energy-Flow-Diagram-revenue](https://user-images.githubusercontent.com/15115882/113712093-fd859780-96e5-11eb-99ed-4752878a332d.png)

**Comment by Cumulus7** [comment]
This would have been my first suggestion as well.
It would allow the amount of power flowing to be seen at first glance without interpreting numbers.

**Comment by reptilex** [comment]
I think it needs to be reeingeered, but the functionality works on this branch: 
https://github.com/reptilex/tesla-style-solar-power-card/tree/energy_flow_diagramm
you need to add a config option:
```yml
energy_flow_diagramm: 1
```
there is also a factor to make lines less or more thick:
```yml
energy_flow_diagramm_line_factor: 2
```
Maybe you can test it?

**Comment by reptilex** [comment]
new release has been created with this feature included

**Comment by oliversoerensen** [comment]
Hi,

thank you for your quick solution! Ist's almost perfect.

As you can see, the PV system is delivering 14.6kW.
The power is split 50/50 to the grid and to the house.
The line from the solar (red arrow) should be twice as thick as the two below.
Or the other way around, the two lower yellow lines would have to be as wide as the line from the house to the car (7kW).

So each segment up to the middle would have to have a separate width.
Would something like that be possible?

Otherwise, thanks for the nice panel!

Oliver
