### ISSUE TITLE
Graphics missing using IOBroker

### ISSUE THREAD

**Issue by Cumulus7** [reptilex/tesla-style-solar-power-card#52]
Hi,

i tried to use your card in IOBrokers Lovelace implementation.
Usually all cards just work fine there (apex-charts or dual-gauge for example).

However your card shows only as follows:
![image](https://user-images.githubusercontent.com/45620107/113934841-85f35d80-97f6-11eb-909b-e376314da4ac.png)

Colors are missing, lines are missing, but at least bubbles are travelling.

My config:

> type: 'custom:tesla-style-solar-power-card'
name: Solaranlage
grid_to_house_entity: sensor.SE_Meter_Netzbezug_berechnet_momentan
generation_to_grid_entity: sensor.SE_Meter_Einspeisung
generation_to_battery_entity: sensor.SE_Batterie_Leistung
generation_to_house_entity: sensor.SE_AC_Leistung_skaliert

Any ideas how to debug this?
(i even tried the latest version here: https://github.com/reptilex/tesla-style-solar-power-card/tree/energy_flow_diagramm)

Greetings and thx in advance,
Markus

**Comment by reptilex** [comment]
It seems like the colours I rely upon from home assistant that are defined there as variables are missing from the css you are using. I have never tried IOBroker can you give me a hint on how to set it up so I can try it? But probably this is a completely different software, so don't get your hopes up to much of me supporting it.

**Comment by Cumulus7** [comment]
Hi,

i changed the colors in your card to:

> var(--info-color) -> var(--label-badge-yellow)
> var(--success-color) -> var(--label-badge-green)
> var(--warning-color) -> var(--label-badge-red)


result:
![image](https://user-images.githubusercontent.com/45620107/113975965-94666700-9840-11eb-9004-934fcb68bdce.png)

Some Icons seem misplaced, but the result is definately better. :-)

I will ask the IOBroker programmer where to define your used colors in their Lovelace implementation.

Additional suggestion:
-maybe we could configure the colors in the card-configuration?
-That way a user could choose to have the battery blue, grid pink and house in bright orange :-).

like:
> house-color: var(--label-badge-yellow)
or maybe even better as entity independet like
> color1: var(--label-badge-yellow)

For easy configuration and backwards-compatibility all values defaulting to your default settings, but changeable.

THX
Markus

**Comment by reptilex** [comment]
There is an event on home assistant that triggers a resize and then everything looks good, seems IOBroker is not doing that.
