### ISSUE TITLE
What triggers a value-Update? My shown values don't change.

### ISSUE THREAD

**Issue by Cumulus7** [reptilex/tesla-style-solar-power-card#53]
Hi,

my shown values do not update :(.

Graphics work now, but the values don't change.

Is there a timer variable that is used?
The values changed ONCE today....

![image](https://user-images.githubusercontent.com/45620107/114011774-e8377700-9865-11eb-9115-2e4caf232895.png)

THX
Markus

**Comment by Cumulus7** [comment]
additional info: even a complete page-reload does NOT update the values...
Very strange...

**Comment by reptilex** [comment]
Well actually a change in the values is being checked by the card and should trigger the update. I'm working with a litElement object and feeding it the values of the entities, so changes in your sensor should trigger a change. But I have the impression that the home assistant changes are triggered even more often.

**Comment by reptilex** [comment]
But I guess you are testing this with IOBroker so this might never work there ... no idea

**Comment by Cumulus7** [comment]
Hi,

i will try to check out the source-code and implement some type of debugging. Since i am pretty short on time at the moment this will take some time. Especially since i normally program C# using VisualStudio. 

Greetings,
Markus
