### ISSUE TITLE
Clickable Bubbles Config

### ISSUE THREAD

**Issue by reesion** [reptilex/tesla-style-solar-power-card#54]
Hi, 

First of all, thank you for your contribution on the card. 

I have been using it with the old release and can't get it working anymore with the new release. Below is my card on the old release. Any assistance will be appreciated.

Thank you in advance.

type: 'custom:tesla-style-solar-power-card'
house_consumption_entity: sensor.current_consumed_positive_2
grid_consumption_entity: sensor.current_grid_positive
grid_feed_in_entity: sensor.current_solar_kwh_sold
solar_consumption_entity: sensor.current_solar_consume
solar_yield_entity: sensor.fronius_panel_status
//show_w_not_kw: 1
//hide_inactive_lines: 1
title: Solar_System

**Comment by reesion** [comment]
I got it working with the following code

type: 'custom:tesla-style-solar-power-card'
grid_entity: sensor.current_grid_positive
house_entity: sensor.current_consumed_positive_2
generation_entity: sensor.fronius_panel_status
grid_to_house_entity: sensor.current_grid_positive
generation_to_grid_entity: sensor.current_solar_kwh_sold
generation_to_house_entity: sensor.current_solar_consume
title: Solar_System


Your readme 'Complete example with all details' are using the wrong entity name.

# 4 main bubble icons for clickable entities
grid_consumption_entity: sensor.grid_consumption
house_consumption_entity: sensor.house_consumption
generation_yield_entity: sensor.solar_yield
battery_consumption_entity: sensor.battery_consumption

instead of

grid_entity
house_entity
generation_entity
battery_entity

**Comment by reptilex** [comment]
thanks for the hint, are you sure that title is working? I thought only 'name' did.

**Comment by reesion** [comment]
Did not realise that the title wasn't showing up

Yes - it only works with 'name'

Thanks.

**Comment by reptilex** [comment]
corrected in latest release
