### ISSUE TITLE
threshold_in_k not working as expected 

### ISSUE THREAD

**Issue by ademobile** [reptilex/tesla-style-solar-power-card#56]
I love this card, however to me it makes sense to show loads in watts if it is less the 1 killowatt. However when using threshold_in_k, I have found two issues:

1. The dot gets stuck at the grid icon (see picture below) if set at 2 or more (e.g. threshold_in_k: 2)
2. Setting threshold_in_k: 1 still shows kW rather than W for loads < 1 kW (i.e. it should show 0-999 W, then 1 kW)

<img width="510" alt="Screenshot 2021-04-12 at 10 38 24" src="https://user-images.githubusercontent.com/25222110/114375013-29889900-9b7c-11eb-9ba5-a7665c4da69c.png">

**Comment by rubenoost** [comment]
This also happens on my config. The dots don't seem to be stuck, but rather move a lot faster, sometimes just blinking in the same spot. Is it possible the kW -> W scaling is also applied on the dot animation speed?

**Comment by ademobile** [comment]
Yes, I am wondering if it is a scalling issue. I have not read through the code fully to understand what it is doing. However I feel it may be better if the code dealt with values as watts and converted to killowatts only when displaying. This would then remove any conversion issues. This would also mean you could do threshold_in_k: 1000 etc. which would make more sense.

**Comment by ademobile** [comment]
I have also spotted whilst the threshold was set the home was still displaying W rather kW even though the value had been converted

<img width="517" alt="Screenshot 2021-04-12 at 11 59 02" src="https://user-images.githubusercontent.com/25222110/114393002-71fe8180-9b91-11eb-974d-e67845d3cd17.png">

**Comment by reptilex** [comment]
Ok, just noticed something went terribly wrong with my commits, sorry for that, will check this and get back to you.

**Comment by reptilex** [comment]
so there is a very deep issue with how I thought I could solve this. It will not work and I will have to redo a lot of stuff. Will take some time. I have to really translate everything to W or kW internally and just decide on how I show any given number otherwise this will never work. Currently I'm summing up w with kw in some instances. Sorry for the trouble. It will take some time to fix.

**Comment by ademobile** [comment]
Thats not problem - I guessed it was a complex issue and I can more than live with it for the time being. I must really learn how to code for home assistant. I have found another issue and will create a seperate bug for that

**Comment by reptilex** [comment]
Found some time for a quick and good solution. This should be fixed, if you can confirm please close the issue if you can confirm. Otherwise I will in a bit.

**Comment by PierreScerri** [comment]
In Version 1.2.2 the threshold_in_k is still not working.

This is my config:

```
type: 'custom:tesla-style-solar-power-card'
grid_entity: sensor.sdm230power
house_entity: sensor.house_power
generation_entity: sensor.sdm120power
grid_to_house_entity: sensor.import_power
generation_to_grid_entity: sensor.export_power
generation_to_house_entity: sensor.solar_use
hide_inactive_lines: 1
threshold_in_k: 1
```

**Comment by ademobile** [comment]
Working for me now (I did have to clear the broswer cache a couple of times):
<img width="510" alt="Screenshot 2021-04-17 at 10 21 34" src="https://user-images.githubusercontent.com/25222110/115108153-c37a8800-9f66-11eb-8c15-6e141a34884a.png">

Thank you again for an excellent componet :-)

**Comment by reptilex** [comment]
@PierreScerri could you make a screenshot of in which way it is not working. Maybe with your sensors also visible?

**Comment by PierreScerri** [comment]
It is working now.  I guess it needed a couple of browser refreshes.

Thank you.

![Screenshot 2021-04-17 at 18 30 32](https://user-images.githubusercontent.com/34303331/115119916-0b230300-9fab-11eb-9306-833146c1c534.png)

**Comment by reptilex** [comment]
tell me about it. Shift reload mostly works, but sometimes you need that and a normal reload. Who knows why could enlighten me :-D
