### ISSUE TITLE
Appliance 1 not displayed in W

### ISSUE THREAD

**Issue by frankitunes** [reptilex/tesla-style-solar-power-card#57]
First of all thanks for this wonderfull cards... 
There is a small issue for Applicance 1. Despite "show_w_not_kw: 1", unit is still in kW however Grid, Generation and House are correctly displayed in W.
Thanks again for th work.
Best
![pv](https://user-images.githubusercontent.com/35428340/114389401-3e255b00-9b95-11eb-95af-faa87e3de54a.gif)

**Comment by reptilex** [comment]
Interesting, will check on my end, but probably something slipped my tests :(

**Comment by reptilex** [comment]
so there is a very deep issue with how I thought I could solve this. It will not work and I will have to redo a lot of stuff. Will take some time.

**Comment by frankitunes** [comment]
No worries, this small bug apart, it is working properly for me.
Thx a lot for your work.

**Comment by reptilex** [comment]
Found some time for a quick and good solution. This should be fixed, if you can confirm please close the issue if you can confirm. Otherwise I will in a bit.

**Comment by frankitunes** [comment]
Thanks for your reactivity! It works but now the W is missing for solar, grid and home...

![image](https://user-images.githubusercontent.com/35428340/115036138-86ae8280-9ecd-11eb-955d-0877c0affb44.png)

Another issue (or misuse from my part), theshold is not working, it nerver switches automatically in kw if higher than "threshold_in_k".
Thx again.

**Comment by reptilex** [comment]
hi. two thing, could you post a screenshot of your sensors when you see this and also your entity definitions? And are you sure you have reset your cache?

**Comment by frankitunes** [comment]
Yep, I answered yes to the question after the update (question was something like "would yo like to clear the cache?").

```
type: 'custom:tesla-style-solar-power-card'
name: Frank's PV Plant
generation_entity: sensor.kostal_pv_power
house_entity: sensor.kostal_home_power
grid_entity: sensor.kostal_home_power_from_grid
appliance1_consumption_entity: sensor.easee_home_fhi_power
appliance1_extra_entity: sensor.mytm3_battery_sensor
generation_to_grid_entity: sensor.kostal_fhi_power_grid_net
generation_to_house_entity: sensor.kostal_home_power_from_pv
grid_to_house_entity: sensor.kostal_home_power_from_grid
threshold_in_k: 1
show_w_not_kw: 0
hide_inactive_lines: 1
change_house_bubble_color_with_flow: 1
energy_flow_diagramm_line_factor: 2
energy_flow_diagramm: 0
generation_icon: 'mdi:solar-power'
appliance1_icon: 'mdi:car-outline'
```

**Comment by reptilex** [comment]
You have to remove show_w_not_kw Possibly this is the error. Could you test? If not, could you remove both threshold_in_k and show_w_not_k and send another screenshot? Thanks

**Comment by reptilex** [comment]
seems to be solved? I haven't been able to recreate your issue.

**Comment by frankitunes** [comment]
Hi, sorry for not givien you any feedback... As you requested I removed threshold_in_k and show_w_not_k and it was ok! I just tried to add ot back and it still working.... very happy thanks for your excellent work.

btw there is a small appearance issue... the line is not well connected... I think it should be a css issue but I newbie with css and I don't know how to solve this...

![image](https://user-images.githubusercontent.com/35428340/115752895-d7751e00-a39a-11eb-9844-ad6e0c9f61bd.png)

**Comment by reptilex** [comment]
Yeah there is an issue about that. In the app it looks ok and under certain widths also, but shrink it or grow it and it does not work. The issue has to do with the way I'm doing the animation, and sadly it's pixel based and therefore that is also pixel based and very hard to make look perfect. Will be done in version 2.0
