### ISSUE TITLE
grid to house entity settting

### ISSUE THREAD

**Issue by nakoukal** [reptilex/tesla-style-solar-power-card#58]
Hello thanks for great visualisation. I use this card with goodwee inverter entities and i don't know how works the grid_to house entity. If in the same time generate grid to house and grid to battery i expect on grid the sum of both  (**active power**), but the grid has only value from grid to house.
![image](https://user-images.githubusercontent.com/6328757/114835805-40282d80-9dd2-11eb-99c1-e444f7f7c006.png)

**Comment by reptilex** [comment]
my bad, I'm missing grid_to_battery flow altogether in the code. I have corrected this and it will be done as soon as I do a push and new release. Sorry.

**Comment by reptilex** [comment]
This is the same problem as Found some time for a quick and good solution. This should be fixed, if you can confirm please close the issue if you can confirm. Otherwise I will in a bit.

**Comment by reptilex** [comment]
Ok. I think this is solved, if not reopen. Thanks
