### ISSUE TITLE
Inverter flow

### ISSUE THREAD

**Issue by ademobile** [reptilex/tesla-style-solar-power-card#59]
In my setup (when complete) my flow would be grid to battery (inverter) then battery to house. Solar would also go in to battery. When I create a card with these entries:
```
- type: 'custom:tesla-style-solar-power-card'
  # threshold_in_k: 1
  grid_to_battery_entity: sensor.electricity_current_import
  generation_to_battery_entity: sensor.solar_to_battery
  battery_to_house_entity: sensor.electricity_to_home
```
This happens:
<img width="505" alt="Screenshot 2021-04-15 at 14 02 09" src="https://user-images.githubusercontent.com/25222110/114873462-36fb8880-9df3-11eb-8ad9-f2cf1cd662a1.png">

As you can see the grid icon is missing.

**Comment by reptilex** [comment]
my bad, I'm missing grid_to_battery flow altogether in the code. I have corrected this and it will be done as soon as I do a push and new release. Sorry.

**Comment by reptilex** [comment]
Found some time for a quick and good solution. This should be fixed, if you can confirm please close the issue if you can confirm. Otherwise I will in a bit.

**Comment by ademobile** [comment]
Thank you so much - looking good:
<img width="506" alt="Screenshot 2021-04-17 at 10 16 26" src="https://user-images.githubusercontent.com/25222110/115108021-1142c080-9f66-11eb-955c-9444de37348f.png">
