### ISSUE TITLE
Should there be a path from Grid to battery?

### ISSUE THREAD

**Issue by B-Hartley** [reptilex/tesla-style-solar-power-card#6]
Should there be a path from Grid to battery?
The battery could be charged by the solar or by the grid?
Should there be lines from both?

So you could charge off peak and use peak ?

btw. I've got the card running with very basic info for house and cars at the moment and fake info for solar and battery.
It's looking like a grey start, thanks !

**Comment by reptilex** [comment]
You are right. Since in my country off peak prises are just starting to be a possibility (suppliers always gave you an average price till a few months ago) I never thought of this case till now. But yes there should be a path from grid to battery. I will try to implement this in the upcoming weeks.

**Comment by B-Hartley** [comment]
Yes. On the tariff I am on. Last night there was negative pricing. So they would have paid me to fill my battery.

**Comment by reptilex** [comment]
Set the grid_to_battery_entity  in the config and there will be one more line now. Let me know if you find an error

**Comment by B-Hartley** [comment]
Can you add this into the "twocars" version please ?

**Comment by reptilex** [comment]
I have now. Can you please test? Be aware that the cars have switched places

**Comment by B-Hartley** [comment]
Thanks.
There seems to be a double line between the house and the lower car.
I can provide a screenshot if you don't know what i mean, or can't see it.

**Comment by reptilex** [comment]
screenshot would be great

**Comment by B-Hartley** [comment]
![screenshot](https://user-images.githubusercontent.com/30037005/97169775-8933e900-1782-11eb-9359-f69bc42631e7.png)

**Comment by reptilex** [comment]
pushed without tests. So if there is a bug let me know, I'll get at it tonight or close the ticket ;)

**Comment by B-Hartley** [comment]
Double line fixed, thanks.
As you see on the screenshot the lines to the cars are a little out of place.
I'm hoping that can be tweaked in due course.

Can't wait to have everything installed so I can use this properly.
They are on the roof now doing the solar !

**Comment by reptilex** [comment]
Yes the line connections are really hard to do unless you put them all in one svg and I haven't figured out how to do that exactly. There is an issue about it open
