### ISSUE TITLE
featrue request - rounding on extra entities

### ISSUE THREAD

**Issue by bigwoof** [reptilex/tesla-style-solar-power-card#62]
I added daily solar energy production and energy consumption as extra entities on my solar and house circles.  This does display the values, however doesn't round the values so the unit is not visible.
I can fix this with a template sensor with rounding, but I think that it may be a nice enhancement for the card, to have a rounding configuration on house_extra_entity (and others).

Just a thought. 

Thanks for the great card 
![image](https://user-images.githubusercontent.com/880522/115185787-e43c0c80-a123-11eb-8520-acfa6d1b672e.png)

**Comment by reptilex** [comment]
Why don't you create template sensors that have the rounding and add them to the extra entities?
