### ISSUE TITLE
Solar panels show as grid and house combined

### ISSUE THREAD

**Issue by Millennium-bug-82** [reptilex/tesla-style-solar-power-card#63]
I'm having some problems with your amazing card. At some point everything worked fine but then when I started to tweak my card my solar power would not display correctly anymore. See the attached picture. It looks like the two other values are combined as a string but I don't know if that's the case.

This is my config:
type: 'custom:tesla-style-solar-power-card'
generation_to_grid_entity: sensor.power_return_now
generation_to_house_entity: sensor.solar_to_house_now
grid_to_house_entity: sensor.power_consumption
generation_icon: 'mdi:solar-power'
threshold_in_k: 1
grid_entity: sensor.power_consumption
house_entity: sensor.actual_power_use_now
generation_entity: sensor.solar_power_now
change_house_bubble_color_with_flow: 1

![power](https://user-images.githubusercontent.com/46250081/115226334-679f3300-a10f-11eb-871a-b73462014034.png)

**Comment by reptilex** [comment]
I find it very strange that you have Watt as a unit there. This should not be the case in any reading. Maybe that is the problem? Any sensors with Watt? My card only recognizes W or kW as units

**Comment by Millennium-bug-82** [comment]
That's probably the problem. The strange thing is that sometimes everything works as expected. Then all off a sudden it doesn't. I will change my sensors to W and try that when I get the chance. Thanks for your quick reply.

**Comment by Millennium-bug-82** [comment]
That fixed it! Everything has been working well today.
