### ISSUE TITLE
Solar values incorrect (double what they should be) w/ Tesla Powerwall

### ISSUE THREAD

**Issue by marx1** [reptilex/tesla-style-solar-power-card#64]
Hello, I'm using a copy-paste of the powerwall config and the solar is roughly double what is actually generated.

These pictures where taken a bit late in the day but during peak the solar was doing 7.5kw, however the card showed solar+grid backfeed power.

Here's what the card looks like:
![image](https://user-images.githubusercontent.com/4861651/115808164-d2b26900-a39e-11eb-89ff-04a22eb143a5.png)
Here's what the powerwall looks like:
![image](https://user-images.githubusercontent.com/4861651/115808184-dfcf5800-a39e-11eb-8861-3793ea980a2a.png)
and here's what HA shows for raw data
![image](https://user-images.githubusercontent.com/4861651/115808316-202ed600-a39f-11eb-9245-8b80b0f77e42.png)

My card config is:
```
type: 'custom:tesla-style-solar-power-card'
name: Power Flow
house_entity: sensor.powerwall_load_now
grid_entity: sensor.tesla_card_grid_consumption
battery_entity: sensor.tesla_card_battery_consumption
generation_entity: sensor.powerwall_solar_now
generation_to_grid_entity: sensor.tesla_card_grid_feed_in
generation_to_house_entity: sensor.tesla_card_solar_consumption
generation_to_battery_entity: sensor.tesla_card_battery_charging
battery_to_house_entity: sensor.tesla_card_battery_consumption
grid_to_house_entity: sensor.tesla_card_grid_consumption
battery_extra_entity: sensor.powerwall_charge
hide_inactive_lines: 1
```
and the configuration.yaml is:

```
  - platform: template
    sensors:
        tesla_card_grid_consumption:
          unique_id: 'tesla_card_5fee6ddd5c1f42a099067ce9dd44e6d1'
          value_template: "{{ states('sensor.powerwall_site_now') | float | max(0) }}"
          device_class: power
          unit_of_measurement: kW
        tesla_card_grid_feed_in:
          unique_id: 'tesla_card_52d22b847ade42c5b4526b2ff15f5aef'
          value_template: "{{ states('sensor.powerwall_site_now') | float | min(0) | abs }}"
          device_class: power
          unit_of_measurement: kW
        tesla_card_solar_consumption:
          unique_id: 'tesla_card_2bb67bd5264f4ec39f141f1722fea085'
          value_template: >-
            {% set solar = states('sensor.powerwall_solar_now') | float %}
            {% set house = states('sensor.powerwall_load_now') | float %}
            {{ solar if house > solar else house }}
          device_class: power
          unit_of_measurement: kW
        tesla_card_battery_consumption:
          unique_id: 'tesla_card_2b7aaa2588e8480aaba586815a84fcd7'
          value_template: "{{ states('sensor.powerwall_battery_now') | float | max(0) }}"
          device_class: power
          unit_of_measurement: kW
        tesla_card_battery_charging:
          unique_id: 'tesla_card_9c46447cf75942ba9ac4bcaca85ba6c5'
          value_template: "{{ states('sensor.powerwall_battery_now') | float | min(0) | abs }}"
          device_class: power
          unit_of_measurement: kW```

**Comment by reptilex** [comment]
I'm starting to think that the one template is wrong now, tesla_card_solar_consumption should be only solar_now - grid_feed_in:
```yml
 tesla_card_solar_consumption:
          unique_id: 'tesla_card_2bb67bd5264f4ec39f141f1722fea085'
          value_template: "{{ (states('sensor.powerwall_solar_now') - states('sensor.tesla_card_grid_feed_in)) | float }}"
          device_class: power
          unit_of_measurement: kW
```
I cannot test this, but if it works let me know to update the configuration. Nice catch

**Comment by marx1** [comment]
There was a missing ' after sensor.tesla_card_grid_feed_in but now it's under reporting:
![image](https://user-images.githubusercontent.com/4861651/115908517-1fd61f80-a41f-11eb-8239-a791aca5cc49.png)
![image](https://user-images.githubusercontent.com/4861651/115908532-25336a00-a41f-11eb-9f86-af6a389802f4.png)

**Comment by reptilex** [comment]
Ok. So I don't understand what load_now and solar_now actually measure. Could you explain?

From what I understand in your last example solar_now should have been 7.6, which does not seem to be the case.

**Comment by marx1** [comment]
Not a problem  - based on the flows in the Tesla power wall itself here's what I gather:
![image](https://user-images.githubusercontent.com/4861651/115929368-8ddd0f80-a43c-11eb-8ed6-a8135e5c1c1d.png)
![image](https://user-images.githubusercontent.com/4861651/115929377-92a1c380-a43c-11eb-8cd7-0fcd28e951f6.png)

solar_now: Solar generated (Currently at 8.4KW)
site_now : utility usage   (Outputting to grid at 6.58kw)
powerwall_battery_now: Battery flow (Currently 0 because it's full)
powerwall_load_now: House load (Currently at 1.8ish kw)
powerwall_charging: True if battery is charging

I do notice that the web interface rounds UP, so 1.78kw becomes 1.8kw etc

**Comment by reptilex** [comment]
well from what I see my last proposal should have worked, although there was one thing missing.
From what I gather the amount of energy that defines the flow from solar to house should be:
solar_now - tesla_card_grid_feed_in - tesla_card_battery_charging
In the example where it was under reporting either solar_now was 0 or it was 5.8 or my yaml was bungled.
But if your solar_now is higher than battery_charging and tesla_grid_feed_in = 0 than with the logic above the rest should be going to your house. If you give me one more example please show both cards and the screen shot of tesla. Thanks

**Comment by marx1** [comment]
![image](https://user-images.githubusercontent.com/4861651/115971471-7e71cb00-a4fd-11eb-8888-030cb7c920f1.png)
![image](https://user-images.githubusercontent.com/4861651/115971478-8e89aa80-a4fd-11eb-9981-c81fb84e995e.png)
![image](https://user-images.githubusercontent.com/4861651/115971487-9a756c80-a4fd-11eb-81cb-b3a4c467ca30.png)

**Comment by marx1** [comment]
I switched modes for a different power flow, and the house is higher load - so house is powered from grid, solar is going to battery:

![image](https://user-images.githubusercontent.com/4861651/115971714-e5dc4a80-a4fe-11eb-8839-0219dc8d4390.png)
![image](https://user-images.githubusercontent.com/4861651/115971710-deb53c80-a4fe-11eb-93c4-97424bc71352.png)
![image](https://user-images.githubusercontent.com/4861651/115971704-cd6c3000-a4fe-11eb-99da-31c436e50d18.png)

this does look correct

**Comment by borski** [comment]
I figured out the proper incantation, after playing with it this morning. The only issue is that the YAML was bumbled above, since you forgot to cast to the correct types. The correct YAML is below:

```yaml
tesla_card_solar_consumption:
        unique_id: 'tesla_card_2bb67bd5264f4ec39f141f1722fea085'
        value_template: "{{ (states('sensor.powerwall_solar_now') | float) - (states('sensor.tesla_card_grid_feed_in') | float ) }}"
        device_class: power
        unit_of_measurement: kW
 ```

This seems to work out great for me:

![image](https://user-images.githubusercontent.com/207674/124171454-74b89680-da5d-11eb-8408-03bb9cfd8e54.png)
![image](https://user-images.githubusercontent.com/207674/124171471-7c783b00-da5d-11eb-8c61-346a61835265.png)

This likely helps fix #74 and #68 too

**Comment by reptilex** [comment]
Swell! Can you post your complete setup. I would like to update the docs

**Comment by borski** [comment]
@reptilex See #76 :)

**Comment by reptilex** [comment]
@borki did us the favor to correct the powerwall docs. Please change your settings accordingly. Thanks .
