### ISSUE TITLE
Day Energy Usage

### ISSUE THREAD

**Issue by mrigau** [reptilex/tesla-style-solar-power-card#65]
Hi, this is more of a question and not an issue...
Is there a way to track the cumulative daily energy usage from the grid and to the grid?.
I already have the now values working ok, but I will love to track the cumulative daily in and out to the grid.
What about weekly and monthly?

Thanks for the advice.
This is a great card,  thanks for it.

**Comment by reptilex** [comment]
Hi. Well this is done outside my card with sensors and other integrations look here:
https://www.home-assistant.io/integrations/integration/
https://www.home-assistant.io/integrations/utility_meter/
https://community.home-assistant.io/t/utility-meter-power-graph/137923/7
