### ISSUE TITLE
Card scales incorrectly with no battery

### ISSUE THREAD

**Issue by ch1ppo** [reptilex/tesla-style-solar-power-card#7]
I'm only displaying Car, Grid House and Solar.

When "Battery" isn't present, the Car floats up over the house.

![Screen Shot 2020-10-25 at 4 14 46 PM](https://user-images.githubusercontent.com/65930087/97098042-7c10ee80-16dd-11eb-8e0f-e445d7b388cb.png)
![Screen Shot 2020-10-25 at 4 15 14 PM](https://user-images.githubusercontent.com/65930087/97098044-7ddab200-16dd-11eb-8cad-d2063eb6b7a6.png)

**Comment by reptilex** [comment]
My bad. Never thought of this scenario and due to the inner paths being in one div and the cars in another this is what happens. Will have to do some testing and will try to correct it soon. But will probably take a week or so.

**Comment by reptilex** [comment]
Found some time, should be fixed in the latest commit. Let me know if it is the case or close the issue ;)

**Comment by ch1ppo** [comment]
Confirming that this now formats correctly
