### ISSUE TITLE
Feature Request: Battery Icon customization with extra entity

### ISSUE THREAD

**Issue by pman07** [reptilex/tesla-style-solar-power-card#72]
The Battery_Icon: customization doesn’t seem to be working for me. Seems to be related to section of code on line 205 that calculates the battery fullness percent. If I remove that portion, the customization works.

**Comment by sebrep** [comment]
As stated in the documentation, this is by design. If you want another icon, then you have to not make the battery bubble be dynamic. So not defining it.

> If you define an extra entity for the battery bubble with the state of charge then the icon will be dynamically replaced with the value of that entity and will override the icon definition above.

don't have this:
```yml
battery_entity: sensor.battery_consumption
```

**Comment by pman07** [comment]
Ok, I'll change this to a feature request. I'd like the option to have a custom icon and the extra entity. I believe currently I'd have to not include the battery_extra_entity not the battery_entity. Correct?

I'd like to have both current charge level and a custom icon. I believe defining battery_icon as anything other than default or null should override the dynamic overwriting. 

To prevent issues with people who copy/paste the card config this should check for the example "mdi:battery" and the null replacement "mdi:battery-medium" to still use the dynamic icon logic.

If others disagree I'll remove this from the pull request and just leave the SVG/line fix.
