### ISSUE TITLE
House Consumption overridden by Battery to House

### ISSUE THREAD

**Issue by beccsjb** [reptilex/tesla-style-solar-power-card#74]
G'day Mate, 
LOVE this front end addon, awesome work.

After configuring it all, it seems that the Battery to House Value seems to override the House Consumption.

ie, it should be able to show the Battery consumption (usually a higher value due to efficiencies)  and then still show the house consumption watts.

See attached image, the house value and battery to house value are the same, despite being given different sensors.
![solardash](https://user-images.githubusercontent.com/43426367/123542168-63386b80-d78b-11eb-80c5-a46cae7c4eae.jpg)

**Comment by sebrep** [comment]
The number shown in the house should be the sum of PV Made, Grid Used and Battery used. So 16.56 + 14.83 + 1.018 Are you sure you have added grid_to_house and generation_to_house as entities?

**Comment by beccsjb** [comment]
Hi Sebrep, thanks for the reply.
Why would the number in the house not simply equal the current House Load in Watts? as Defined in House Consumption Entity.

grid_to_house and generation_to_house have been added. When the grid is being used and pv is being made, they display their correct lines and wattages etc.

But the defined 'house_consumption_entity' seems to be ignored once the 'battery_to_house_entity' is defined.

type: custom:tesla-style-solar-power-card
show_w_not_kw: 1
grid_consumption_entity: sensor.inverter_grid_watts
house_consumption_entity: sensor.inverter_loads_watts
grid_to_house_entity: sensor.grid_to_house
generation_to_house_entity: sensor.solar_to_house
generation_to_battery: sensor.solar_to_battery
battery_entity: sensor.pylontech_watts
battery_extra_entity: sensor.pylontech_soc_total
battery_to_house_entity: sensor.battery_to_house
generation_extra_entity: sensor.inverter_daily_made_kwh
grid_extra_entity: sensor.inverter_daily_grid_used_kwh
appliance1_consumption_entity: sensor.hws_watts
appliance1_extra_entity: sensor.hws_kwhd
appliance1_icon: mdi:fire
appliance2_consumption_entity: sensor.power_water_pump_power
appliance2_extra_entity: sensor.power_water_pump_energy
appliance2_icon: mdi:water
appliance3_consumption_entity: sensor.power_septic_line_pump_power
appliance3_extra_entity: sensor.power_septic_line_pump_energy
appliance3_icon: mdi:toilet
hide_inactive_lines: 1
threshold_in_k: 1

**Comment by beccsjb** [comment]
I think I've now got everything working except generation to battery working. 

The battery just will not show up a positive indication, nor create a line from the Solar up the top, down to the battery.

Any thoughts?

**Comment by reptilex** [comment]
have you checked on your sensor.solar_to_battery is it showing anything when the battery is being loaded?

**Comment by beccsjb** [comment]
G’day Reptilex, yeah the solar_to_battery shows the data correctly.

**Comment by reptilex** [comment]
your yml is wrong it should be called: generation_to_battery_entity

**Comment by beccsjb** [comment]
OH MY GOSH! Wow, how did i overlook that! I'm so sorry to have wasted your time. 

Thank you very much, nice to have it working. I've lost hours to that simple mistake!
