### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by Yassith** [reptilex/tesla-style-solar-power-card#77]
Hi,

First thank you for the work done to create and support th plugin.

As for the issue I have been trying to make it display correct values but it seems to me that my config is correct and the math behind is not doing the right calculations.

I have PV installed where I get momentary readings of power generation.
On the main grid line I have bi- directional meter which gives 1 value either positive for consumption or negative for sending energy to the grid.

I have configured specific sensors to hold only positive values and to separate consumption and production on the main meter (grid connection)

Here are some pictures

![image](https://user-images.githubusercontent.com/74787098/124951987-26cf0000-e014-11eb-8b9e-c7954c8bbdca.png)
![image](https://user-images.githubusercontent.com/74787098/124952271-64338d80-e014-11eb-913e-71638d128f89.png)

What I don't understand is why I'm getting such large number under the house icon.

Can you advise please.

Regards
Yassith 

EDIT:

I corrected minor mistakes however the problem of large kW number under house icon remains

**Comment by Yassith** [comment]
I think there is more to it as the numbers don't match

![image](https://user-images.githubusercontent.com/74787098/124953803-bf19b480-e015-11eb-97d9-3b50fd2d93ca.png)

**Comment by reptilex** [comment]
It seems to me that your licznik_house_poweractive sensor is wrong in terms of it's unit. It should be W and not kW. Maybe you have to edit the sensors to add a unit_of_measurement attribute.
