### ISSUE TITLE
Layout and lines not as expected

### ISSUE THREAD

**Issue by davidfhudson** [reptilex/tesla-style-solar-power-card#8]
Firstly I think this card is going to be excellent. Pulling together data from various different systems is exactly what I need - Myenergi, SolarEdge, Tesla apps all missing something.

On installing, however I cant get the layout to be correct. the lines are not in the right place. May well be user error - very new at this. my layout is below - explains the situation best. Data is all correct 

![teslasolar](https://user-images.githubusercontent.com/68943322/97105805-b36ba500-16b5-11eb-9339-d42a6ef31f08.PNG)

**Comment by reptilex** [comment]
Thanks for the comment and great bug report, with image. This was happening after the latest update of Homeassistant. I just pushed a new version correcting this a few days ago. Are you sure you have installed it and reset all your caches (Browser cache, homeassistant cache, mobile app cache) ?

**Comment by davidfhudson** [comment]
Thanks for the prompt response. I had the latest code but not latest Home Assistant. Upgrading that To 0.116.4 did the job. Works great now. 

Will test 2 car version now and also a +1 for the feature request to show a line from grid to battery (which I do when power is super cheap or negative)
