### ISSUE TITLE
Change optional extra entities from W to kW

### ISSUE THREAD

**Issue by silviudc** [reptilex/tesla-style-solar-power-card#80]
I want to add optional extra entities and my values are in kW yet it still displays them in W, once that goes to over 10000W the text goes outside of the bubble and is just not that easy to read in W vs kW

![image](https://user-images.githubusercontent.com/17740184/126863434-c042c2d8-5481-4258-ac15-9e15699349d2.png)

Maybe add a reverse option to this:
`show_w_not_kw: 1`

**Comment by reptilex** [comment]
the extra entities texts are sadly not being checked for units and converted, since you could have any type of text there. So you will have to create template sensors for those.
