### ISSUE TITLE
Not showing negative values when exporting to grid

### ISSUE THREAD

**Issue by cp1983** [reptilex/tesla-style-solar-power-card#84]
Hi

I noticed that the grid is no longer showing a negative value when exporting excess energy from solar. Noticed in the code that you have changed it to Abs.

Can we have the negative value back as an option, or maybe change the color of the grid circle/icon when exporting to make it easier to see if you are exporting or not. Looking at the bubbles to determine which way the power is going takes a little more effort.

Thanks

Christian

**Comment by reptilex** [comment]
This was part of a PR and it missed my review ... I think the newest version corrected this, but I haven't made a release yet

**Comment by One1Tick** [comment]
Hi, On mine it shows negative value (when selling to grid) if I use stay in W. If I choose to use kW instead of W above 1000 W, it shows negative value till -999W and it turns abs() above -999W  (ie -1200W => 1.2kW).
Thanks fir your work.

**Comment by reptilex** [comment]
wow, will have to test this .... that seems an ugly bug. I thought I had repaired the negative values in my last release, but will need to check now.

**Comment by reptilex** [comment]
I cannot confirm this bug, it seems I fixed it, if you find it again, let me know please.

**Comment by cp1983** [comment]
I can confirm, latest version works as expected. Version 1.2.4 did not show negative values when kW is selected. 1.3.0 does. Thanks for the update.
