### ISSUE TITLE
Alignment of battery to grid line

### ISSUE THREAD

**Issue by mrgadget** [reptilex/tesla-style-solar-power-card#85]
First off, great card, thanks for your work on this one.

Really minor issue, but would be great to see it fixed (or be told what my issue is!).  For me, the line into the battery node from the grid node doesn't line up with the others, as seen in image:

![image](https://user-images.githubusercontent.com/700522/129099744-8263741f-774f-401e-96a4-74b2026a4345.png)

**Comment by FredericMa** [comment]
I'm seeing the same:
![image](https://user-images.githubusercontent.com/7840263/130670289-de9c0f13-0c52-47a8-a6bc-25330047b6ab.png)

**Comment by reptilex** [comment]
Ups, the thing is someone else corrected the rest, but like me he cannot buy from grid to battery probably, because he forgot to correct this one ... I'm swamped with other stuff but will try to get to this on the weekend. Let's see

**Comment by mrgadget** [comment]
I'm happy to do a PR for this as well as the gapped lines which means next to no work for you - let me know.

**Comment by reptilex** [comment]
Please do, Ill add it, ASAP. Thanks a lot @mrgadget

**Comment by sebrep** [comment]
I think it's in the latest release

**Comment by reptilex** [comment]
yep
