### ISSUE TITLE
Missing entities for initial setup?

### ISSUE THREAD

**Issue by adamurban** [reptilex/tesla-style-solar-power-card#87]
New powerwall/solar customer here.. Am trying to follow the readme to get the card loaded, but the standard powerwall integration seems to be missing most of the needed sensors?

I have:
```yaml
  - binary_sensor.grid_status
  - binary_sensor.powerwall_charging
  - binary_sensor.powerwall_connected_to_tesla
  - sensor.powerwall_battery_now
  - sensor.powerwall_load_now
  - sensor.powerwall_site_now
  - sensor.powerwall_solar_now
  - binary_sensor.powerwall_status
  ```
Am I using the wrong integration for pulling data in?

**Comment by reptilex** [comment]
You need to create  those template sensors because powerwall uses sensors as positive and negative and the card requires differentiated sensors to work. Adding those and then using them on the card configuration you should be fine.
