### ISSUE TITLE
Lovelace YAML is not valid

### ISSUE THREAD

**Issue by remyderuysscher** [reptilex/tesla-style-solar-power-card#9]
Can you provide a valid YAML lovelace card? The example is not working. Something like:
``
      - entities:
          - grid_consumption_entity: sensor.dsmr_reading_electricity_currently_delivered
          - grid_feed_in_entity: sensor.grid_feed_in
          - house_consumption_entity: sensor.house_consumption
          - solar_consumption_entity: sensor.solar_consumption
          - solar_yield_entity: sensor.solar_yield
        type: 'custom:tesla-style-solar-power-card'
``

**Comment by reptilex** [comment]
I have never done a card configuration in YAML, only in the lovelace frontend. Are you sure you need the " - entities:" keyword? In lovelace I have exactly what is in the README.md

**Comment by reptilex** [comment]
My lovelace yaml looks like this:
`title: Home
views:
  - badges:
      - entity: sensor.solar_yield
      - entity: sensor.stromz_leistung
      - entity: sensor.house_consumption
      - entity: sensor.marvin_range_sensor
      - entity: sensor.openweathermap_temperature
      - entity: sensor.openweathermap_cloud_coverage
    cards:
      - battery_charge_entity: sensor.battery_charge
        battery_charging_entity: sensor.battery_charging
        battery_consumption_entity: sensor.battery_consumption
        car_battery_entity: sensor.marvin_battery_sensor
        car_charging_entity: sensor.marvin_current_charging
        entity: sensor.house_consumption
        grid_consumption_entity: sensor.grid_consumption
        grid_feed_in_entity: sensor.grid_feed_in
        house_consumption_entity: sensor.house_consumption
        solar_consumption_entity: sensor.solar_consumption
        solar_yield_entity: sensor.solar_yield
        type: 'custom:tesla-style-solar-power-card'`

**Comment by PierreScerri** [comment]
I have the same issue.  This is a screen grab of the sensors and values and the corresponding card error.

![Screenshot 2020-11-15 at 13 01 37](https://user-images.githubusercontent.com/34303331/99184412-d6ccc180-2742-11eb-927e-6cf074ee8159.png)

**Comment by reptilex** [comment]
If you update to my latest version you don't need entity anymore. This was a remnant of the base card I did this with and older versions had this problem

**Comment by PierreScerri** [comment]
Thank you. That is very nice. Well done.
