### ISSUE TITLE
Problem with values

### ISSUE THREAD

**Issue by pczolee** [reptilex/tesla-style-solar-power-card#98]
Hello.

My Problem is, that the values shown is different than the real values.
For example here you can see that the solar power is 1761W, but the card show 3305W
![kép](https://user-images.githubusercontent.com/27812638/146363168-11b2279c-52b8-45ca-9075-c03a7516a8fb.png)

The grid meter showing 265W import, but I have -265W (so 265W export)
![kép](https://user-images.githubusercontent.com/27812638/146363438-acb6bc9d-4318-4f13-8123-99674c4d1266.png)
![kép](https://user-images.githubusercontent.com/27812638/146363460-244b88c2-15d2-49f0-8982-e8d85b652938.png)

The house itself looks good:
![kép](https://user-images.githubusercontent.com/27812638/146363547-3f8a421c-fd2c-42f0-af68-104b8824158c.png)

This is my config is:     
>  - type: custom:tesla-style-solar-power-card

        show_w_not_kw: 1
        name: Current state
        generation_to_grid_entity: sensor.feedin_power
        generation_to_house_entity: sensor.load_power
        generation_to_battery_entity: sensor.zero_power
        battery_to_house_entity: sensor.zero_power
        house_entity: sensor.load_power
        grid_entity: sensor.total_power
        generation_entity: sensor.inverter_power
        grid_icon: mdi:transmission-tower
        generation_icon: mdi:solar-panel-large
        house_icon: mdi:home
        battery_icon: mdi:battery
        appliance1_icon: mdi:server
        appliance2_icon: mdi:server

Thanks

**Comment by reptilex** [comment]
Well you are not using the card right. Read the documentation you need entities for these flows:
    generation_to_grid_entity
    generation_to_battery_entity
    generation_to_house_entity
    grid_to_battery_entity (optional)
    grid_to_house_entity
    battery_to_grid_entity (optional)
    battery_to_house_entity
If you don't have the flow as an entity you need to create templates.
The entities substract and add to the bubbles like:
battery_to_house will substract from the battery bubble/icon and add to house bubble/icon.
